{
 "title": "TIBCO EMS Server Details",
 "tags": [
  "EMS",
  "TIBCO",
  "Prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Server",
    "query": {
     "query": "label_values(tibco_ems_server_uptime,Server)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Message Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "tibco_ems_server_message_mem_bytes{Server=~\"$Server\"}",
     "legendFormat": "{{Server}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tibco_ems_server_connections{Server=~\"$Server\"}",
     "legendFormat": "All:{{Server}}"
    },
    {
     "expr": "tibco_ems_server_client_connections{Server=~\"$Server\"}",
     "legendFormat": "Client:{{Server}}"
    },
    {
     "expr": "tibco_ems_server_admin_connections{Server=~\"$Server\"}",
     "legendFormat": "Admin:{{Server}}"
    }
   ]
  },
  {
   "title": "Async DB Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "tibco_ems_server_async_db_bytes{Server=~\"$Server\"}",
     "legendFormat": "{{Server}}"
    }
   ]
  },
  {
   "title": "Disk Write Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "tibco_ems_server_storage_write_byte_rate{Server=~\"$Server\"}",
     "legendFormat": "{{Server}}"
    }
   ]
  },
  {
   "title": "Sync DB Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "tibco_ems_server_sync_db_bytes{Server=~\"$Server\"}",
     "legendFormat": "{{Server}}"
    }
   ]
  },
  {
   "title": "Disk Read Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "tibco_ems_server_storage_write_byte_rate{Server=~\"$Server\"}",
     "legendFormat": "{{Server}}"
    }
   ]
  }
 ]
}