{
 "title": "TIBCO EMS Queues",
 "tags": [
  "TIBCO",
  "EMS",
  "Prometheus",
  "Queue"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Server",
    "query": {
     "query": "label_values(tibco_ems_server_queue_consumers,Server)"
    }
   },
   {
    "name": "Queue",
    "query": {
     "query": "label_values(tibco_ems_server_queue_consumers{Server=~\"$Server\"},queue)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "EMS Queues",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(queue) (last_over_time(tibco_ems_server_queue_pending_messages{Server=~\"$Server\", queue=~\"$Queue\"}[$__interval]))",
     "legendFormat": "{{queue}}"
    },
    {
     "expr": "sum by(queue) (last_over_time(tibco_ems_server_queue_pending_message_bytes{Server=~\"$Server\", queue=~\"$Queue\"}[$__interval]))",
     "legendFormat": "{{queue}}"
    },
    {
     "expr": "sum by(queue) (last_over_time(tibco_ems_server_queue_consumers{Server=~\"$Server\", queue=~\"$Queue\"}[$__interval]))",
     "legendFormat": "{{queue}}"
    },
    {
     "expr": "sum by(queue) (last_over_time(tibco_ems_server_queue_inbound_message_rate{Server=~\"$Server\", queue=~\"$Queue\"}[$__interval]))",
     "legendFormat": "{{queue}}"
    },
    {
     "expr": "sum by(queue) (last_over_time(tibco_ems_server_queue_outbound_message_rate{Server=~\"$Server\", queue=~\"$Queue\"}[$__interval]))",
     "legendFormat": "{{queue}}"
    },
    {
     "expr": "sum by(queue) (last_over_time(tibco_ems_server_queue_inbound_byte_rate{Server=~\"$Server\", queue=~\"$Queue\"}[$__interval]))",
     "legendFormat": "{{queue}}"
    },
    {
     "expr": "sum by(queue) (last_over_time(tibco_ems_server_queue_outbound_byte_rate{Server=~\"$Server\", queue=~\"$Queue\"}[$__interval]))",
     "legendFormat": "{{queue}}"
    },
    {
     "expr": "sum by(queue) (last_over_time(tibco_ems_server_queue_pending_persistent_messages{Server=~\"$Server\", queue=~\"$Queue\"}[$__interval]))",
     "legendFormat": "{{queue}}"
    },
    {
     "expr": "sum by(queue) (last_over_time(tibco_ems_server_queue_pending_persistent_message_bytes{Server=~\"$Server\", queue=~\"$Queue\"}[$__interval]))",
     "legendFormat": "{{queue}}"
    },
    {
     "expr": "sum by(queue) (last_over_time(tibco_ems_server_queue_inbound_messages_total{Server=~\"$Server\", queue=~\"$Queue\"}[$__interval]))",
     "legendFormat": "{{queue}}"
    },
    {
     "expr": "sum by(queue) (last_over_time(tibco_ems_server_queue_outbound_messages_total{Server=~\"$Server\", queue=~\"$Queue\"}[$__interval]))",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Message Rate In",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "tibco_ems_server_queue_inbound_message_rate{Server=~\"$Server\", queue=~\"$Queue\"}",
     "legendFormat": "{{Server}}:{{queue}}"
    }
   ]
  },
  {
   "title": "Message Rate Out",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "M/s" } },
   "targets": [
    {
     "expr": "tibco_ems_server_queue_outbound_message_rate{Server=~\"$Server\", queue=~\"$Queue\"}",
     "legendFormat": "{{Server}}:{{queue}}"
    }
   ]
  },
  {
   "title": "Byte Rate In",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "tibco_ems_server_queue_inbound_byte_rate{Server=~\"$Server\", queue=~\"$Queue\"}",
     "legendFormat": "{{Server}}:{{queue}}"
    }
   ]
  },
  {
   "title": "Byte Rate Out",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "tibco_ems_server_queue_outbound_byte_rate{Server=~\"$Server\", queue=~\"$Queue\"}",
     "legendFormat": "{{Server}}:{{queue}}"
    }
   ]
  },
  {
   "title": "Pending Messages",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tibco_ems_server_queue_pending_messages{Server=~\"$Server\", queue=~\"$Queue\"}",
     "legendFormat": "{{Server}}:{{queue}}"
    }
   ]
  },
  {
   "title": "Pending Message Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "tibco_ems_server_queue_pending_message_bytes{Server=~\"$Server\", queue=~\"$Queue\"}",
     "legendFormat": "{{Server}}:{{queue}}"
    }
   ]
  }
 ]
}