{
 "title": "TIBCO EMS Topics",
 "tags": [
  "TIBCO",
  "EMS",
  "Prometheus",
  "Topic"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Server",
    "label": "Server",
    "query": {
     "query": "label_values(tibco_ems_server_topic_consumers,Server)"
    }
   },
   {
    "name": "Topic",
    "query": {
     "query": "label_values({Server=~\"$Server\"},topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "EMS Topics",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(topic) (last_over_time(tibco_ems_server_topic_pending_messages{Server=~\"$Server\", topic=~\"$Topic\"}[$__interval]))",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "sum by(topic) (last_over_time(tibco_ems_server_topic_pending_message_bytes{Server=~\"$Server\", topic=~\"$Topic\"}[$__interval]))",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "sum by(topic) (last_over_time(tibco_ems_server_topic_subscriptions{Server=~\"$Server\", topic=~\"$Topic\"}[$__interval]))",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "sum by(topic) (last_over_time(tibco_ems_server_topic_inbound_message_rate{Server=~\"$Server\", topic=~\"$Topic\"}[$__interval]))",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "sum by(topic) (last_over_time(tibco_ems_server_topic_outbound_message_rate{Server=~\"$Server\", topic=~\"$Topic\"}[$__interval]))",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "sum by(topic) (last_over_time(tibco_ems_server_topic_inbound_byte_rate{Server=~\"$Server\", topic=~\"$Topic\"}[$__interval]))",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "sum by(topic) (last_over_time(tibco_ems_server_topic_outbound_byte_rate{Server=~\"$Server\", topic=~\"$Topic\"}[$__interval]))",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "sum by(topic) (last_over_time(tibco_ems_server_topic_pending_persistent_messages{Server=~\"$Server\", topic=~\"$Topic\"}[$__interval]))",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "sum by(topic) (last_over_time(tibco_ems_server_topic_pending_persistent_message_bytes{Server=~\"$Server\", topic=~\"$Topic\"}[$__interval]))",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "sum by(topic) (last_over_time(tibco_ems_server_topic_inbound_messages_total{Server=~\"$Server\", topic=~\"$Topic\"}[$__interval]))",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "sum by(topic) (last_over_time(tibco_ems_server_topic_outbound_messages_total{Server=~\"$Server\", topic=~\"$Topic\"}[$__interval]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Message Rate In",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "M/s" } },
   "targets": [
    {
     "expr": "tibco_ems_server_topic_inbound_message_rate{Server=~\"$Server\", topic=~\"$Topic\"}",
     "legendFormat": "{{Server}}:{{topic}}"
    }
   ]
  },
  {
   "title": "Message Rate Out",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "M/s" } },
   "targets": [
    {
     "expr": "tibco_ems_server_topic_outbound_message_rate{Server=~\"$Server\", topic=~\"$Topic\"}",
     "legendFormat": "{{Server}}:{{topic}}"
    }
   ]
  },
  {
   "title": "Byte Rate In",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "tibco_ems_server_topic_inbound_byte_rate{Server=~\"$Server\", topic=~\"$Topic\"}",
     "legendFormat": "{{Server}}:{{topic}}"
    }
   ]
  },
  {
   "title": "Byte Rate Out",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "tibco_ems_server_topic_outbound_byte_rate{Server=~\"$Server\", topic=~\"$Topic\"}",
     "legendFormat": "{{Server}}:{{topic}}"
    }
   ]
  },
  {
   "title": "Pending Message Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tibco_ems_server_topic_pending_messages",
     "legendFormat": "{{Server}}:{{topic}}"
    }
   ]
  },
  {
   "title": "Pending Message Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "tibco_ems_server_topic_pending_message_bytes{Server=~\"$Server\", topic=~\"$Topic\"}",
     "legendFormat": "{{Server}}:{{topic}}"
    }
   ]
  }
 ]
}