{
 "title": "FTL: Persistence",
 "tags": [
  "TIBCO",
  "FTL",
  "Persistence",
  "Prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "RealmID",
    "query": {
     "query": "query_result(count(last_over_time(tibco_ftl_store_messages{Cluster !~ \"_config_cluster\"}[${__range}])) by (RealmID))"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "query_result(count(last_over_time(tibco_ftl_store_quorum_number_info{Cluster !~ \"_config_cluster\", RealmID = \"${RealmID}\", state = \"history\"}[${__range}])) by (Cluster))"
    }
   },
   {
    "name": "PersistenceServer",
    "query": {
     "query": "query_result(count(last_over_time(tibco_ftl_store_messages{RealmID = \"${RealmID}\", Cluster =~ \"${Cluster}\"}[${__range}])) by (PersistenceServer))"
    }
   },
   {
    "name": "Store",
    "query": {
     "query": "query_result(count(last_over_time(tibco_ftl_store_messages{RealmID = \"${RealmID}\", Cluster =~ \"${Cluster}\", PersistenceServer =~ \"${PersistenceServer}\", Context !~ \"^(_GlobalNonReplicated_|_GlobalReplicated_|_LocalNonReplicated_|_LocalReplicated_).+$\"}[${__range}])) by (Context))"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align:center\"><h1>FTL: Persistence</h1><h2>$Cluster</h2></div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Operation Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(tibco_ftl_store_quorum_number_info{RealmID=\"$RealmID\", PersistenceServer=~\"$PersistenceServer\", Cluster=\"$Cluster\", state=\"history\"}[$__rate_interval])",
     "legendFormat": "{{PersistenceServer}}"
    }
   ]
  },
  {
   "title": "Pending Updates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tibco_ftl_store_updates{RealmID=\"$RealmID\", PersistenceServer=~\"$PersistenceServer\", Cluster=\"$Cluster\", state=\"pending\"}",
     "legendFormat": "{{PersistenceServer}}"
    }
   ]
  },
  {
   "title": "Committed Updates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tibco_ftl_store_updates{RealmID=\"$RealmID\", PersistenceServer=~\"$PersistenceServer\", Cluster=\"$Cluster\", state=\"committed\"}",
     "legendFormat": "{{PersistenceServer}}"
    }
   ]
  },
  { "title": "$Store", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }, "repeat": "Store" },
  {
   "title": "Persistence Message Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tibco_ftl_store_messages{RealmID=\"$RealmID\", Cluster=\"$Cluster\", Context=~\"$Store\"}",
     "legendFormat": "{{PersistenceServer}}:{{Context}}"
    }
   ]
  },
  {
   "title": "Persistence Message Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "tibco_ftl_store_message_bytes{RealmID=\"$RealmID\", Cluster=\"$Cluster\", Context=~\"$Store\"}",
     "legendFormat": "{{PersistenceServer}}:{{Context}}"
    }
   ]
  },
  {
   "title": "Percent of Maximum Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "tibco_ftl_store_message_bytes{RealmID=\"$RealmID\", Cluster=\"$Cluster\", Context=~\"$Store\"} / on(Cluster,PersistenceServer,Context) tibco_ftl_store_limit_bytes{RealmID=\"$RealmID\", Cluster=\"$Cluster\", Context=~\"$Store\"}",
     "legendFormat": "{{PersistenceServer}}:{{Context}}"
    }
   ]
  },
  {
   "title": "Durable Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tibco_ftl_store_durables{RealmID=\"$RealmID\", Cluster=\"$Cluster\", Context=~\"$Store\"}",
     "legendFormat": "{{PersistenceServer}}:{{Context}}"
    }
   ]
  },
  {
   "title": "Inbound message rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "rate(tibco_ftl_received_ftl_messages{RealmID=\"$RealmID\", Cluster=\"$Cluster\", Context=~\"$Store\"}[$__rate_interval])",
     "legendFormat": "{{PersistenceServer}}:{{Context}}"
    }
   ]
  },
  {
   "title": "Outbound message rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "rate(tibco_ftl_sent_ftl_messages{RealmID=\"$RealmID\", Cluster=\"$Cluster\", Context=~\"$Store\"}[$__rate_interval])",
     "legendFormat": "{{PersistenceServer}}:{{Context}}"
    }
   ]
  },
  {
   "title": "Swap Message Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tibco_ftl_store_swap_messages{RealmID=\"$RealmID\", Cluster=\"$Cluster\", Context=~\"$Store\"}",
     "legendFormat": "{{PersistenceServer}}:{{Context}}"
    }
   ]
  },
  {
   "title": "Swap Message Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "tibco_ftl_store_message_bytes{RealmID=\"$RealmID\", Cluster=\"$Cluster\", Context=~\"$Store\"}",
     "legendFormat": "{{PersistenceServer}}:{{Context}}"
    }
   ]
  }
 ]
}