{
 "title": "FTL Applications: Overview",
 "tags": [
  "TIBCO",
  "FTL",
  "Applications",
  "Prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "RealmID",
    "query": {
     "query": "query_result(count(last_over_time(tibco_ftl_store_messages{Cluster !~ \"_config_cluster\"}[${__range}])) by (RealmID))"
    }
   },
   { "name": "GroupBy", "label": "Group by", "query": "Application,ClientLabel" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align:center\"><h1>FTL Applications: Overview</h1></div> "
   },
   "targets": [
    {}
   ]
  },
  { "title": "Number of Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(Application) (tibco_ftl_clients_total{RealmID=\"$RealmID\", Type=\"service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Satellites",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(Application) (tibco_ftl_satellites_total{RealmID=\"$RealmID\", Type=\"service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FTL Servers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(Application) (tibco_ftl_ftlservers_total{RealmID=\"$RealmID\", Type=\"service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Persistence Servers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(tibco_ftl_store_messages{RealmID=\"$RealmID\",Cluster!~\"_config_cluster\"}) by (PersistenceServer))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "FTL Rates by $GroupBy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "FTL Message Publish Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum by ($GroupBy) (rate(tibco_ftl_sent_messages{RealmID=\"$RealmID\",Type=\"application\"}[$__rate_interval])) ",
     "legendFormat": "{{$GroupBy}}"
    }
   ]
  },
  {
   "title": "FTL Message Delivery Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum by ($GroupBy) (rate(tibco_ftl_received_messages{RealmID=\"$RealmID\",Type=\"application\"}[$__rate_interval]))",
     "legendFormat": "{{$GroupBy}}"
    }
   ]
  },
  {
   "title": "FTL Data Send Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by ($GroupBy) (rate(tibco_ftl_sent_bytes{RealmID=\"$RealmID\",Type=\"application\"}[$__rate_interval]) * 8) ",
     "legendFormat": "{{$GroupBy}}"
    }
   ]
  },
  {
   "title": "FTL Data Receive Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by ($GroupBy) (rate(tibco_ftl_received_bytes{RealmID=\"$RealmID\",Type=\"application\"}[$__rate_interval]) * 8) ",
     "legendFormat": "{{$GroupBy}}"
    }
   ]
  },
  {
   "title": "Total CPU Time Rate of Increase",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }
  },
  {
   "title": "Applications",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(tibco_ftl_cpu_time_seconds{RealmID=\"$RealmID\", Type=\"application\"}[$__rate_interval])",
     "legendFormat": "{{Application}}({{ClientID}})"
    }
   ]
  }
 ]
}