{
 "title": "FTL: Disk Persistence",
 "tags": [
  "TIBCO",
  "FTL",
  "Persistence",
  "Prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "RealmID",
    "query": {
     "query": "query_result(count(last_over_time(tibco_ftl_store_messages{Cluster !~ \"_config_cluster\"}[${__range}])) by (RealmID))"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "query_result(count(last_over_time(tibco_ftl_store_quorum_number_info{Cluster !~ \"_config_cluster\", RealmID = \"${RealmID}\", state = \"history\"}[${__range}])) by (Cluster))"
    }
   },
   {
    "name": "PersistenceServer",
    "query": {
     "query": "query_result(count(last_over_time(tibco_ftl_store_messages{RealmID = \"${RealmID}\", Cluster =~ \"${Cluster}\"}[${__range}])) by (PersistenceServer))"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align:center\"><h1>FTL: Disk Persistence</h1><h2>$Cluster</h2></div>"
   },
   "targets": [
    {}
   ]
  },
  { "title": "$PersistenceServer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }, "repeat": "PersistenceServer" },
  {
   "title": "Volume Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "tibco_ftl_pserver_disk_usage_bytes{RealmID=\"$RealmID\", PersistenceServer=~\"$PersistenceServer\", Cluster=\"$Cluster\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "tibco_ftl_pserver_disk_available_bytes{RealmID=\"$RealmID\", PersistenceServer=~\"$PersistenceServer\", Cluster=\"$Cluster\"}",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "FTL Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "tibco_ftl_pserver_disk_allocated_bytes{RealmID=\"$RealmID\", PersistenceServer=~\"$PersistenceServer\", Cluster=\"$Cluster\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "tibco_ftl_pserver_disk_used_bytes{RealmID=\"$RealmID\", PersistenceServer=~\"$PersistenceServer\", Cluster=\"$Cluster\"}",
     "legendFormat": "InUse"
    }
   ]
  },
  {
   "title": "FTL Disk Usage Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "tibco_ftl_pserver_disk_usage_bytes{RealmID=\"$RealmID\", PersistenceServer=~\"$PersistenceServer\", Cluster=\"$Cluster\"}",
     "legendFormat": "Disk Used"
    },
    {
     "expr": "tibco_ftl_pserver_disk_usage_limit_bytes{RealmID=\"$RealmID\", PersistenceServer=~\"$PersistenceServer\", Cluster=\"$Cluster\"}",
     "legendFormat": "Disk usage limit"
    }
   ]
  },
  {
   "title": "Volume Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tibco_ftl_pserver_disk_usage_bytes{RealmID=\"$RealmID\", Cluster=\"$Cluster\", PersistenceServer=~\"$PersistenceServer\"} / on(Cluster,PersistenceServer) (tibco_ftl_pserver_disk_capacity_bytes{RealmID=\"$RealmID\", Cluster=~\"$Cluster\", PersistenceServer=~\"$PersistenceServer\"} > 0)",
     "legendFormat": "{{PersistenceServer}}"
    }
   ]
  },
  {
   "title": "FTL Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tibco_ftl_pserver_disk_used_bytes{RealmID=\"$RealmID\", Cluster=\"$Cluster\", PersistenceServer=~\"$PersistenceServer\"} / on(Cluster,PersistenceServer) (tibco_ftl_pserver_disk_allocated_bytes{RealmID=\"$RealmID\", Cluster=~\"$Cluster\", PersistenceServer=~\"$PersistenceServer\"} > 0)",
     "legendFormat": "{{PersistenceServer}} Used"
    }
   ]
  },
  {
   "title": "FTL Disk Usage Limit",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tibco_ftl_pserver_disk_usage_bytes{RealmID=\"$RealmID\", Cluster=\"$Cluster\", PersistenceServer=~\"$PersistenceServer\"} / on(Cluster,PersistenceServer) (tibco_ftl_pserver_disk_usage_limit_bytes{RealmID=\"$RealmID\", Cluster=~\"$Cluster\", PersistenceServer=~\"$PersistenceServer\"} > 0)",
     "legendFormat": "{{PersistenceServer}} Usage Limit"
    }
   ]
  }
 ]
}