{
 "title": "FTL Services: Overview",
 "tags": [
  "TIBCO",
  "FTL",
  "Services",
  "Prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "RealmID",
    "query": {
     "query": "query_result(count(last_over_time(tibco_ftl_store_messages{Cluster !~ \"_config_cluster\"}[${__range}])) by (RealmID))"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align:center\"><h1>FTL Services: Overview</h1></div>"
   }
  },
  { "title": "Number of Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(Application) (tibco_ftl_clients_total{RealmID=\"$RealmID\", Type=\"service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Satellites",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(Application) (tibco_ftl_satellites_total{RealmID=\"$RealmID\", Type=\"service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FTL Servers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(Application) (tibco_ftl_ftlservers_total{RealmID=\"$RealmID\", Type=\"service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Persistence Servers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(tibco_ftl_store_messages{RealmID=\"$RealmID\",Cluster!~\"_config_cluster\"}) by (PersistenceServer))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "FTL Rates by Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "FTL Send Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (Application) (rate(tibco_ftl_sent_bytes{RealmID=\"$RealmID\",Type=\"service\"}[$__rate_interval]) * 8) ",
     "legendFormat": "{{Application}}"
    }
   ]
  },
  {
   "title": "FTL Receive Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (Application) (rate(tibco_ftl_received_bytes{RealmID=\"$RealmID\",Type=\"service\"}[$__rate_interval]) * 8) ",
     "legendFormat": "{{Application}}"
    }
   ]
  },
  {
   "title": "Total CPU Time Rate of Increase",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }
  },
  {
   "title": "FTL Services",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(tibco_ftl_cpu_time_seconds{RealmID=\"$RealmID\", Type=\"service\"}[$__rate_interval])",
     "legendFormat": "{{Application}}({{ServiceID}})"
    }
   ]
  }
 ]
}