{
 "title": "FTL: Process",
 "tags": [
  "TIBCO",
  "FTL",
  "Prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "RealmID",
    "query": {
     "query": "query_result(count(last_over_time(tibco_ftl_store_messages{Cluster !~ \"_config_cluster\"}[${__range}])) by (RealmID))"
    }
   },
   { "name": "SelectBy", "query": "Application,ClientLabel" },
   {
    "name": "Application",
    "query": {
     "query": "query_result(count(last_over_time(tibco_ftl_cpu_time_seconds{Cluster !~ \"_config_cluster\"}[${__range}])) by (${SelectBy}))"
    }
   },
   {
    "name": "Process",
    "query": {
     "query": "query_result(count(last_over_time(tibco_ftl_cpu_time_seconds{Cluster !~ \"_config_cluster\", ${SelectBy} = \"${Application}\"}[${__range}])) by (ComponentID))"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align:center\"><h1>FTL: Process Information</h1></div>"
   }
  },
  {
   "title": "CPU Time Rate of Increase",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(tibco_ftl_cpu_time_user_seconds{RealmID=\"$RealmID\", ComponentID=\"$Process\"}[$__rate_interval])",
     "legendFormat": "User CPU Time"
    },
    {
     "expr": "rate(tibco_ftl_cpu_time_system_seconds{RealmID=\"$RealmID\", ComponentID=\"$Process\"}[$__rate_interval])",
     "legendFormat": "System CPU Time"
    }
   ]
  },
  {
   "title": "Process RSS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "tibco_ftl_process_rss_bytes{RealmID=\"$RealmID\", ComponentID=\"$Process\"}",
     "legendFormat": "RSS"
    },
    {
     "expr": "tibco_ftl_process_peak_rss_bytes{RealmID=\"$RealmID\", ComponentID=\"$Process\"}",
     "legendFormat": "Peak RSS"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "tibco_ftl_process_vm_bytes{RealmID=\"$RealmID\", ComponentID=\"$Process\"}",
     "legendFormat": "Virtual Memory"
    }
   ]
  },
  {
   "title": "FTL Data Send Rate by Transport",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(tibco_ftl_sent_bytes{RealmID=\"$RealmID\", ComponentID=\"$Process\"}[$__rate_interval]) * 8",
     "legendFormat": "{{Context}}"
    }
   ]
  },
  {
   "title": "FTL Message Send Rate by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "rate(tibco_ftl_sent_messages{RealmID=\"$RealmID\", ComponentID=\"$Process\"}[$__rate_interval])",
     "legendFormat": "{{Context}}"
    }
   ]
  },
  {
   "title": "FTL Data Receive Rate by Transport",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(tibco_ftl_received_bytes{RealmID=\"$RealmID\", ComponentID=\"$Process\"}[$__rate_interval]) * 8",
     "legendFormat": "{{Context}}"
    }
   ]
  },
  {
   "title": "FTL Message Receive Rate by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "rate(tibco_ftl_received_messages{RealmID=\"$RealmID\", ComponentID=\"$Process\"}[$__rate_interval]) * 8",
     "legendFormat": "{{Context}}"
    }
   ]
  },
  {
   "title": "Queue Backlog",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tibco_ftl_queue_backlog_messages{RealmID=\"$RealmID\", ComponentID=\"$Process\"}",
     "legendFormat": "{{Context}}"
    }
   ]
  },
  {
   "title": "Queue Discards",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tibco_ftl_queue_discarded_messages{RealmID=\"$RealmID\", ComponentID=\"$Process\"}",
     "legendFormat": "{{Context}}"
    }
   ]
  },
  {
   "title": "Data Loss",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tibco_ftl_dataloss_events{RealmID=\"$RealmID\", ComponentID=\"$Process\"}",
     "legendFormat": "{{Context}}"
    }
   ]
  }
 ]
}