{
 "title": "eFTL Channels",
 "tags": [
  "TIBCO",
  "eFTL",
  "Prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "RealmID",
    "query": {
     "query": "query_result(count(last_over_time(tibco_ftl_store_messages{Cluster !~ \"_config_cluster\"}[${__range}])) by (RealmID))"
    }
   },
   {
    "name": "Channel",
    "query": {
     "query": "query_result(count(last_over_time(tibco_ftl_eftl_connections{RealmID = \"${RealmID}\", type = \"current\"}[${__range}])) by (Context))"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align:center\"><h1>eFTL Channels</h1></div>"
   }
  },
  { "title": "Number of Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Current Connection Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum by(Application) (tibco_ftl_eftl_connections{RealmID=\"$RealmID\", Context=~\"$Channel\", state=\"current\"})",
     "legendFormat": "{{Context}}"
    }
   ]
  },
  {
   "title": "Max Connection Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 3 },
   "targets": [
    {
     "expr": "sum by(Application) (tibco_ftl_eftl_connections{RealmID=\"$RealmID\", Context=~\"$Channel\", state=\"max\"})",
     "legendFormat": "{{Context}}"
    }
   ]
  },
  {
   "title": "Pending Connection Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "sum by(Application) (tibco_ftl_eftl_connections{RealmID=\"$RealmID\", Context=~\"$Channel\", state=\"pending\"})",
     "legendFormat": "{{Context}}"
    }
   ]
  },
  {
   "title": "Suspended Connection Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
   "targets": [
    {
     "expr": "sum by(Application) (tibco_ftl_eftl_connections{RealmID=\"$RealmID\", Context=~\"$Channel\", state=\"suspended\"})",
     "legendFormat": "{{Context}}"
    }
   ]
  },
  {
   "title": "Inbound eFTL Message Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(tibco_ftl_eftl_received_messages{RealmID=\"$RealmID\",Context=~\"$Channel\"}[$__rate_interval]) ",
     "legendFormat": "{{Context}}"
    }
   ]
  },
  {
   "title": "Outbound eFTL Message Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(tibco_ftl_eftl_sent_messages{RealmID=\"$RealmID\",Context=~\"$Channel\"}[$__rate_interval]) ",
     "legendFormat": "{{Context}}"
    }
   ]
  },
  {
   "title": "Discarded eFTL Messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "tibco_ftl_eftl_discarded_messages{RealmID=\"$RealmID\",Context=~\"$Channel\"}",
     "legendFormat": "{{Context}}"
    }
   ]
  }
 ]
}