{
 "title": "FTL Services: Queues/Loss",
 "tags": [
  "TIBCO",
  "FTL",
  "Services",
  "Prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "RealmID",
    "query": {
     "query": "query_result(count(last_over_time(tibco_ftl_store_messages{Cluster !~ \"_config_cluster\"}[${__range}])) by (RealmID))"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align:center\"><h1>FTL Services: Queues/Loss</h1></div> "
   },
   "targets": [
    {}
   ]
  },
  { "title": "Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Backlog",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tibco_ftl_queue_backlog_messages{RealmID=\"$RealmID\", Type=\"service\"}",
     "legendFormat": "{{Application}}({{ServiceID}}):{{Context}}"
    }
   ]
  },
  {
   "title": "Discards",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tibco_ftl_queue_discarded_messages{RealmID=\"$RealmID\", Type=\"service\"}",
     "legendFormat": "{{Application}}({{ServiceID}}):{{Context}}"
    }
   ]
  },
  { "title": "Data Loss", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Data Loss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tibco_ftl_dataloss_events{RealmID=\"$RealmID\", Type=\"service\"}",
     "legendFormat": "{{Application}}({{ServiceID}}):{{Context}}"
    }
   ]
  }
 ]
}