{
 "title": "FTL Applications: Compact",
 "tags": [
  "TIBCO",
  "FTL",
  "Applications",
  "Prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "RealmID",
    "query": {
     "query": "query_result(count(last_over_time(tibco_ftl_store_messages{Cluster !~ \"_config_cluster\"}[${__range}])) by (RealmID))"
    }
   },
   { "name": "GroupBy", "label": "Group by", "query": "Application,ClientLabel" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align:center\"><h1>FTL Applications: Compact</h1></div> "
   },
   "targets": [
    {}
   ]
  },
  { "title": "FTL Rates by $GroupBy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "FTL Message Publish Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum by ($GroupBy) (rate(tibco_ftl_sent_messages{RealmID=\"$RealmID\",Type=\"application\"}[$__rate_interval])) ",
     "legendFormat": "{{$GroupBy}}"
    }
   ]
  },
  {
   "title": "FTL Data Send Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by ($GroupBy) (rate(tibco_ftl_sent_bytes{RealmID=\"$RealmID\",Type=\"application\"}[$__rate_interval]) * 8) ",
     "legendFormat": "{{$GroupBy}}"
    }
   ]
  },
  {
   "title": "FTL Message Delivery Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum by ($GroupBy) (rate(tibco_ftl_received_messages{RealmID=\"$RealmID\",Type=\"application\"}[$__rate_interval]))",
     "legendFormat": "{{$GroupBy}}"
    }
   ]
  },
  {
   "title": "FTL Data Receive Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by ($GroupBy) (rate(tibco_ftl_received_bytes{RealmID=\"$RealmID\",Type=\"application\"}[$__rate_interval]) * 8) ",
     "legendFormat": "{{$GroupBy}}"
    }
   ]
  },
  {
   "title": "FTL Rates by Endpoint/Transport",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }
  },
  {
   "title": "FTL Message Publish Rate by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum by (Context) (rate(tibco_ftl_sent_messages{RealmID=\"$RealmID\",Type=\"application\"}[$__rate_interval])) ",
     "legendFormat": "{{Context}}"
    }
   ]
  },
  {
   "title": "FTL Message Delivery Rate by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum by (Context) (rate(tibco_ftl_received_messages{RealmID=\"$RealmID\",Type=\"application\"}[$__rate_interval]))",
     "legendFormat": "{{Context}}"
    }
   ]
  },
  {
   "title": "FTL Data Send Rate by Transport",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (Context) (rate(tibco_ftl_sent_bytes{RealmID=\"$RealmID\",Type=\"application\"}[$__rate_interval]) * 8) ",
     "legendFormat": "{{Context}}"
    }
   ]
  },
  {
   "title": "FTL Data Receive Rate by Transport",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (Context) (rate(tibco_ftl_received_bytes{RealmID=\"$RealmID\",Type=\"application\"}[$__rate_interval]) * 8) ",
     "legendFormat": "{{Context}}"
    }
   ]
  },
  { "title": "Queues/Loss", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Queue Backlog",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tibco_ftl_queue_backlog_messages{RealmID=\"$RealmID\", Type=\"application\"}",
     "legendFormat": "{{Application}}({{ClientID}}):{{Context}}"
    }
   ]
  },
  {
   "title": "Queue Discards",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tibco_ftl_queue_discarded_messages{RealmID=\"$RealmID\", Type=\"application\"}",
     "legendFormat": "{{Application}}({{ClientID}}):{{Context}}"
    }
   ]
  },
  {
   "title": "Data Loss",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tibco_ftl_dataloss_events{RealmID=\"$RealmID\", Type=\"application\"}",
     "legendFormat": "{{Application}}({{ClientID}}):{{Context}}"
    }
   ]
  },
  { "title": "CPU Time Rate of Increase", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Total CPU Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(tibco_ftl_cpu_time_seconds{RealmID=\"$RealmID\", Type=\"application\"}[$__rate_interval])",
     "legendFormat": "{{Application}}({{ClientID}})"
    }
   ]
  },
  {
   "title": "User/System CPU Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(tibco_ftl_cpu_time_user_seconds{RealmID=\"$RealmID\", Type=\"application\"}[$__rate_interval])",
     "legendFormat": "{{Application}}({{ClientID}}) User"
    },
    {
     "expr": "rate(tibco_ftl_cpu_time_system_seconds{RealmID=\"$RealmID\", Type=\"application\"}[$__rate_interval])",
     "legendFormat": "{{Application}}({{ClientID}}) System"
    }
   ]
  },
  { "title": "Number of Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(Application) (tibco_ftl_clients_total{RealmID=\"$RealmID\", Type=\"service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Satellites",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(Application) (tibco_ftl_satellites_total{RealmID=\"$RealmID\", Type=\"service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FTL Servers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(Application) (tibco_ftl_ftlservers_total{RealmID=\"$RealmID\", Type=\"service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Persistence Servers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(tibco_ftl_store_messages{RealmID=\"$RealmID\",Cluster!~\"_config_cluster\"}) by (PersistenceServer))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Client State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Client State",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tibco_ftl_clients{RealmID=\"$RealmID\", Type=\"service\"}",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}