{
 "title": "FTL Applications: Rates",
 "tags": [
  "TIBCO",
  "FTL",
  "Applications",
  "Prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "RealmID",
    "query": {
     "query": "query_result(count(last_over_time(tibco_ftl_store_messages{Cluster !~ \"_config_cluster\"}[${__range}])) by (RealmID))"
    }
   },
   { "name": "GroupBy", "label": "Group by", "query": "Application,ClientLabel" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align:center\"><h1>FTL Applications: Rates</h1></div> "
   },
   "targets": [
    {}
   ]
  },
  { "title": "FTL Rates by $GroupBy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "FTL Message Publish Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum by($GroupBy) (rate(tibco_ftl_sent_messages{RealmID=\"$RealmID\", Type=\"application\"}[$__rate_interval]))",
     "legendFormat": "{{$GroupBy}}"
    }
   ]
  },
  {
   "title": "FTL Message Delivery Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum by ($GroupBy) (rate(tibco_ftl_received_messages{RealmID=\"$RealmID\",Type=\"application\"}[$__rate_interval]))",
     "legendFormat": "{{$GroupBy}}"
    }
   ]
  },
  {
   "title": "FTL Data Send Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by ($GroupBy) (rate(tibco_ftl_sent_bytes{RealmID=\"$RealmID\",Type=\"application\"}[$__rate_interval]) * 8) ",
     "legendFormat": "{{$GroupBy}}"
    }
   ]
  },
  {
   "title": "FTL Data Receive Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by ($GroupBy) (rate(tibco_ftl_received_bytes{RealmID=\"$RealmID\",Type=\"application\"}[$__rate_interval]) * 8) ",
     "legendFormat": "{{$GroupBy}}"
    }
   ]
  },
  { "title": "FTL Rates by Endpoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "FTL Message Publish Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (Context) (rate(tibco_ftl_sent_messages{RealmID=\"$RealmID\",Type=\"application\"}[$__rate_interval])) ",
     "legendFormat": "{{Context}}"
    }
   ]
  },
  {
   "title": "FTL Message Delivery Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (Context) (rate(tibco_ftl_received_messages{RealmID=\"$RealmID\",Type=\"application\"}[$__rate_interval]))",
     "legendFormat": "{{Context}}"
    }
   ]
  },
  { "title": "FTL Rates by Transport", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "FTL Data Send Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (Context) (rate(tibco_ftl_sent_bytes{RealmID=\"$RealmID\",Type=\"application\"}[$__rate_interval]) * 8) ",
     "legendFormat": "{{Context}}"
    }
   ]
  },
  {
   "title": "FTL Data Receive Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (Context) (rate(tibco_ftl_received_bytes{RealmID=\"$RealmID\",Type=\"application\"}[$__rate_interval]) * 8) ",
     "legendFormat": "{{Context}}"
    }
   ]
  }
 ]
}