{
 "title": "FTL Services: CPU Time/Memory Usage",
 "tags": [
  "TIBCO",
  "FTL",
  "Services",
  "Prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "RealmID",
    "query": {
     "query": "query_result(count(last_over_time(tibco_ftl_store_messages{Cluster !~ \"_config_cluster\"}[${__range}])) by (RealmID))"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align:center\"><h1>FTL Services: CPU Time/Memory Usage</h1></div>"
   }
  },
  {
   "title": "FTL Services CPU Time Rate of Increase",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }
  },
  {
   "title": "Total CPU Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(tibco_ftl_cpu_time_seconds{RealmID=\"$RealmID\", Type=\"service\"}[$__rate_interval])",
     "legendFormat": "{{Application}}({{ServiceID}})"
    }
   ]
  },
  {
   "title": "User/System CPU Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(tibco_ftl_cpu_time_user_seconds{RealmID=\"$RealmID\", Type=\"service\"}[$__rate_interval])",
     "legendFormat": "{{Application}}({{ServiceID}}) User"
    },
    {
     "expr": "rate(tibco_ftl_cpu_time_system_seconds{RealmID=\"$RealmID\", Type=\"service\"}[$__rate_interval])",
     "legendFormat": "{{Application}}({{ServiceID}}) System"
    }
   ]
  },
  { "title": "FTL Services Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "RSS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "tibco_ftl_process_rss_bytes{RealmID=\"$RealmID\", Type=\"service\"}",
     "legendFormat": "{{Application}}({{ServiceID}}) RSS"
    },
    {
     "expr": "tibco_ftl_process_peak_rss_bytes{RealmID=\"$RealmID\", Type=\"service\"}",
     "legendFormat": "{{Application}}({{ServiceID}}) Peak"
    }
   ]
  },
  {
   "title": "VM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "tibco_ftl_process_vm_bytes{RealmID=\"$RealmID\", Type=\"service\"}",
     "legendFormat": "{{Application}}({{ServiceID}})"
    }
   ]
  }
 ]
}