{
 "title": "Producers",
 "tags": [
  "Kafka",
  "AKD",
  "Producer",
  "Prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Job",
    "query": {
     "query": "label_values(kafka_server_ControllerMutation_queue_size,job)"
    }
   },
   {
    "name": "Instance",
    "label": "Producer",
    "query": {
     "query": "label_values(kafka_producer_kafka_metrics_count_count{job=\"$Job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Key Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Kafka Brokers", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 } },
  { "title": "Active Controllers", "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 } },
  { "title": "Partitions", "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 } },
  { "title": "Under-Replicated Partitions", "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 } },
  { "title": "Offline Partitions", "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 } },
  { "title": "ZooKeeper Nodes", "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 } },
  { "title": "$Instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "Instance" },
  {
   "title": "Compression Rate",
   "type": "timeseries",
   "description": "The average compression rate of record batches.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_compression_rate_avg{job=\"$Job\", instance=\"$Instance\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Response Rate",
   "type": "timeseries",
   "description": "Responses received per second.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_response_rate{job=\"$Job\", instance=\"$Instance\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "The average number of requests sent per second.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_request_rate{job=\"$Job\", instance=\"$Instance\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "description": "The average request latency in milliseconds.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_request_latency_avg{job=\"$Job\", instance=\"$Instance\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Outgoing Byte Rate",
   "type": "timeseries",
   "description": "The average number of outgoing bytes sent per second to all servers.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_outgoing_byte_rate{job=\"$Job\", instance=\"$Instance\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Batch Size",
   "type": "timeseries",
   "description": "The average number of bytes sent per partition per request.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_batch_size_avg{job=\"$Job\", instance=\"$Instance\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "I/O Wait Time",
   "type": "timeseries",
   "description": "The average length of time the I/O thread spent waiting for a socket ready for reads or writes in nanoseconds.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_io_wait_time_ns_avg{job=\"$Job\", instance=\"$Instance\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  }
 ]
}