{
 "title": "Topics",
 "tags": [
  "Kafka",
  "AKD",
  "Topics",
  "Prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Job",
    "query": {
     "query": "label_values(kafka_server_ControllerMutation_queue_size,job)"
    }
   },
   {
    "name": "Instance",
    "query": {
     "query": "label_values(kafka_server_ControllerMutation_queue_size{job=\"$Job\"},instance)"
    }
   },
   {
    "name": "Topic",
    "query": {
     "query": "label_values(kafka_server_BrokerTopicMetrics_Count{job=\"$Job\", instance=~\"$Instance\"},topic)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Key Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Kafka Brokers", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 } },
  { "title": "Active Controllers", "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 } },
  { "title": "Partitions", "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 } },
  { "title": "Under-Replicated Partitions", "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 } },
  { "title": "Offline Partitions", "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 } },
  { "title": "ZooKeeper Nodes", "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 } },
  { "title": "$Topic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "Topic" },
  {
   "title": "Messages In",
   "type": "timeseries",
   "description": "The Messages In Rate shows the number of individual messages, regardless of their size, produced per second. This is useful as a growth metric as a different measure of producer traffic.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(kafka_server_BrokerTopicMetrics_Count{job=\"$Job\", instance=~\"$Instance\", topic=\"$Topic\", name=\"MessagesInPerSec\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes In",
   "type": "timeseries",
   "description": "Bytes In, expressed in bytes per second, is useful as a measurement of how much message traffic your brokers are receiving from producing clients. This is a good metric to trend over time to help you determine when you need to expand the cluster or do other growth-related work. It is also useful for evaluating if one broker in a cluster is receiving more traffic than the others, which would indicate that it is necessary to rebalance the partitions in the cluster.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(kafka_server_BrokerTopicMetrics_Count{job=\"$Job\", instance=~\"$Instance\", topic=\"$Topic\", name=\"BytesInPerSec\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes Out",
   "type": "timeseries",
   "description": "The Bytes Out Rate shows the rate at which consumers are reading messages out. The outbound bytes rate may scale differently than the inbound bytes rate, thanks to Kafka’s capacity to handle multiple consumers with ease. There are many deployments of Kafka where the outbound rate can easily be six times the inbound rate!",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(kafka_server_BrokerTopicMetrics_Count{job=\"$Job\", instance=~\"$Instance\", topic=\"$Topic\", name=\"BytesOutPerSec\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Fetch Requests",
   "type": "timeseries",
   "description": "Fetch request rate.",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(kafka_server_BrokerTopicMetrics_Count{job=\"$Job\", instance=~\"$Instance\", topic=\"$Topic\", name=\"TotalFetchRequestsPerSec\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Produce Requests",
   "type": "timeseries",
   "description": "Produce request rate.",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(kafka_server_BrokerTopicMetrics_Count{job=\"$Job\", instance=~\"$Instance\", topic=\"$Topic\", name=\"TotalProduceRequestsPerSec\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}