{
 "title": "Cluster Member System Statistics",
 "tags": [
  "AKD",
  "Kafka",
  "Broker",
  "Producer",
  "Consumer",
  "ZooKeeper",
  "Connector",
  "Stream",
  "Prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Job",
    "query": {
     "query": "label_values(kafka_server_ControllerMutation_queue_size,job)"
    }
   },
   {
    "name": "Instance",
    "label": "Member",
    "query": {
     "query": "label_values(process_cpu_seconds_total{job=\"$Job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Key Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Kafka Brokers", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 } },
  { "title": "Active Controllers", "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 } },
  { "title": "Partitions", "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 } },
  { "title": "Under-Replicated Partitions", "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 } },
  { "title": "Offline Partitions", "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 } },
  { "title": "ZooKeeper Nodes", "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 } },
  {
   "title": "Free Physical Memory",
   "type": "timeseries",
   "description": "The amount of free physical memory in the host system.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_FreePhysicalMemorySize{job=\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used Physical Memory",
   "type": "timeseries",
   "description": "The amount of physical memory in use in the host system.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_TotalPhysicalMemorySize{job=\"$Job\", instance=~\"$Instance\"} - on(job,instance) java_lang_OperatingSystem_FreePhysicalMemorySize{job=\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Committed Virtual Memory",
   "type": "timeseries",
   "description": "The amount of virtual memory guaranteed to be available for use by the JVM.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_CommittedVirtualMemorySize{job=\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "timeseries",
   "description": "Heap Memory Usage is the runtime data area from which memory for all class instances and arrays are allocated. It is created at the Java virtual machine start-up. Heap memory for objects is reclaimed by an automatic memory management system which is known as a garbage collector.\n\nThe memory for the heap does not need to be contiguous.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "java_lang_Memory_NonHeapMemoryUsage_committed{job=\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instace}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "description": "Percentage of CPU utilization by the selected process, and by the system as a whole.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_ProcessCpuLoad{job=\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}} Process"
    },
    {
     "expr": "java_lang_OperatingSystem_CpuLoad{job=\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}} System"
    }
   ]
  },
  {
   "title": "Non-Heap Memory Usage",
   "type": "timeseries",
   "description": "The Java virtual machine has a method area that is shared among all threads. The method area belongs to non-heap memory. It stores per-class structures such as a runtime constant pool, field and method data, and the code for methods and constructors. It is created at the Java virtual machine start-up.\n\nThe method area is logically part of the heap but a Java virtual machine implementation may choose not to either garbage collect or compact it.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "java_lang_Memory_NonHeapMemoryUsage_used{job=\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System Load Average",
   "type": "timeseries",
   "description": "The average load in the host system.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_SystemLoadAverage{job=\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "description": "The current number of open file descriptors.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_OpenFileDescriptorCount{job=\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Time Rate of Change",
   "type": "timeseries",
   "description": "The rate of change (increase) in the CPU time used per second by this process. A fairly constant value generally indicates the process is doing its normal work. Some peaks and valleys are expected as the process workload changes.\n\nA constantly or sharply increasing rate of change may be indicative of a problem.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(java_lang_OperatingSystem_ProcessCpuTime{job=\"$Job\", instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}