{
 "title": "ZooKeeper Overview",
 "description": "ZooKeeper Overview",
 "tags": [
  "Kafka",
  "AKD",
  "ZooKeeper",
  "Prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Job",
    "query": {
     "query": "label_values(kafka_server_ControllerMutation_queue_size,job)"
    }
   },
   {
    "name": "Instance",
    "label": "ZooKeeper",
    "query": {
     "query": "label_values({job=\"$Job\", __name__=~\"org_apache_ZooKeeperService_ReplicatedServer_.*_AvgRequestLatency|org_apache_ZooKeeperService_StandaloneServer_.*_AvgRequestLatency\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$Instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "Instance",
   "targets": [
    {}
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "description": "Average, maximum, and minimum time it takes for the server to respond to a client request (since the server was started).",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "{job=\"$Job\", instance=~\"$Instance\", __name__=~\"org_apache_ZooKeeperService_ReplicatedServer_.*_AvgRequestLatency|org_apache_ZooKeeperService_StandaloneServer_.*_AvgRequestLatency\" }",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ZNode Count",
   "type": "timeseries",
   "description": "Number of znodes in the Zookeeper namespace.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{job=\"$Job\", instance=~\"$Instance\", __name__=~\"org_apache_ZooKeeperService_ReplicatedServer_.*_NodeCount|org_apache_ZooKeeperService_StandaloneServer_.*_NodeCount\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Packets",
   "type": "timeseries",
   "description": "Number of packets sent and received per second.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate({job=\"$Job\", instance=~\"$Instance\", __name__=~\"org_apache_ZooKeeperService_ReplicatedServer_.*_PacketsSent\", name3=\"\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "rate({job=\"$Job\", instance=~\"$Instance\", __name__=~\"org_apache_ZooKeeperService_StandaloneServer_.*_PacketsSent\", name1=\"\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Watch Count",
   "type": "timeseries",
   "description": "Number of watchers setup over ZooKeeper nodes.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{job=\"$Job\", instance=~\"$Instance\", __name__=~\"org_apache_ZooKeeperService_ReplicatedServer_.*_WatchCount|org_apache_ZooKeeperService_StandaloneServer_.*_WatchCount\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "description": "Percentage of CPU utilization by the selected process, and by the system as a whole.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_ProcessCpuLoad{job=\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}} Process"
    },
    {
     "expr": "java_lang_OperatingSystem_CpuLoad{job=\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}} System"
    }
   ]
  },
  {
   "title": "CPU Time Rate of Change",
   "type": "timeseries",
   "description": "The rate of change (increase) in the CPU time used per second by this process. A fairly constant value generally indicates the process is doing its normal work. Some peaks and valleys are expected as the process workload changes.\n\nA constantly or sharply increasing rate of change may be indicative of a problem.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(java_lang_OperatingSystem_ProcessCpuTime{job=\"$Job\", instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System Load Average",
   "type": "timeseries",
   "description": "The average load in the host system.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_SystemLoadAverage{job=\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}