{
 "title": "Broker Message and Data Rates",
 "tags": [
  "Kafka",
  "Broker",
  "AKD",
  "Prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Job",
    "query": {
     "query": "label_values(kafka_server_ControllerMutation_queue_size,job)"
    }
   },
   {
    "name": "Instance",
    "label": "Broker",
    "query": {
     "query": "label_values(kafka_server_ControllerMutation_queue_size{job=\"$Job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Key Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  { "title": "Kafka Brokers", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 } },
  { "title": "Active Controllers", "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 } },
  { "title": "Partitions", "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 } },
  { "title": "Under-Replicated Partitions", "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 } },
  { "title": "Offline Partitions", "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 } },
  { "title": "ZooKeeper Nodes", "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 } },
  {
   "title": "Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Messages In",
   "type": "timeseries",
   "description": "The Messages In Rate shows the number of individual messages, regardless of their size, produced per second. This is useful as a growth metric as a different measure of producer traffic.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum by(instance) (kafka_server_BrokerTopicMetrics_MeanRate{job=\"$Job\", instance=~\"$Instance\", name=\"MessagesInPerSec\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes In",
   "type": "timeseries",
   "description": "Bytes In, expressed in bytes per second, is useful as a measurement of how much message traffic your brokers are receiving from producing clients. This is a good metric to trend over time to help you determine when you need to expand the cluster or do other growth-related work. It is also useful for evaluating if one broker in a cluster is receiving more traffic than the others, which would indicate that it is necessary to rebalance the partitions in the cluster.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(instance) (kafka_server_BrokerTopicMetrics_MeanRate{job=\"$Job\", instance=~\"$Instance\", name=\"BytesInPerSec\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes Out",
   "type": "timeseries",
   "description": "The Bytes Out Rate shows the rate at which consumers are reading messages out. The outbound bytes rate may scale differently than the inbound bytes rate, thanks to Kafka’s capacity to handle multiple consumers with ease. There are many deployments of Kafka where the outbound rate can easily be six times the inbound rate!",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(kafka_server_BrokerTopicMetrics_Count{job=\"$Job\", instance=~\"$Instance\", name=\"BytesOutPerSec\", topic=\"\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Bytes",
   "type": "timeseries",
   "description": "Request bytes received per second.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(kafka_network_RequestMetrics_Count{job=\"$Job\", instance=~\"$Instance\", name=\"RequestBytes\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "description": "Requests received per second.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(kafka_network_RequestMetrics_Count{job=\"$Job\", instance=~\"$Instance\", name=\"RequestsPerSec\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Expires",
   "type": "timeseries",
   "description": "The ZooKeeper session has expired. When a session expires, we can have leader changes and even a new controller. It is important to keep an eye on the number of such events across a Kafka cluster and if the overall number is high, then we have a few recommendations:\n\n- Check the health of your network\n- Check for garbage collection issues and tune it accordingly\n- If necessary, increase the session time out by setting the value of zookeeper.session.timeout.ms.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kafka_server_SessionExpireListener_Count{job=\"$Job\", instance=~\"$Instance\", name=\"ZooKeeperExpiresPerSec\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ZooKeeper to Broker Mean Latency",
   "type": "timeseries",
   "description": "Mean latency millseconds for ZooKeeper requests from the broker.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(kafka_server_ZooKeeperClientMetrics_Count{job=\"$Job\", instance=~\"$Instance\", name=\"ZooKeeperRequestLatencyMs\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replication Bytes In",
   "type": "timeseries",
   "description": "Bytes in rate from other brokers.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(kafka_server_BrokerTopicMetrics_Count{job=\"$Job\", instance=~\"$Instance\", name=\"ReplicationBytesInPerSec\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replication Bytes Out",
   "type": "timeseries",
   "description": "Bytes out rate to other brokers.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(kafka_server_BrokerTopicMetrics_Count{job=\"$Job\", instance=~\"$Instance\", name=\"ReplicationBytesOutPerSec\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Number of errors in responses counted per-request-type, per-error-code. If a response contains multiple errors, all are taken into account for rate change.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(kafka_network_RequestMetrics_Count{job=\"$Job\", instance=~\"$Instance\", name=\"ErrorsPerSec\", error!=\"NONE\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Internal Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network Processor Avg Idle Percent",
   "type": "timeseries",
   "description": "The average fraction of time the network processors are idle.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kafka_network_SocketServer_Value{job=\"$Job\", instance=~\"$Instance\", name=\"NetworkProcessorAvgIdlePercent\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Handler Avg Idle Percent",
   "type": "timeseries",
   "description": "The average fraction of time the request handler threads are idle.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kafka_server_KafkaRequestHandlerPool_MeanRate{job=\"$Job\", instance=~\"$Instance\", name=\"RequestHandlerAvgIdlePercent\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}