{
 "title": "Overview",
 "tags": [
  "Kafka",
  "AKD",
  "Prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Job",
    "query": {
     "query": "label_values(kafka_server_ControllerMutation_queue_size,job)"
    }
   },
   {
    "name": "Instance",
    "query": {
     "query": "label_values(kafka_server_ControllerMutation_queue_size{job=\"$Job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Key Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  { "title": "Kafka Brokers", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 } },
  { "title": "Active Controllers", "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 } },
  { "title": "Partitions", "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 } },
  { "title": "Under-Replicated Partitions", "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 } },
  { "title": "Offline Partitions", "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 } },
  { "title": "ZooKeeper Nodes", "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 } },
  {
   "title": "Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Messages In",
   "type": "timeseries",
   "description": "The Messages In Rate shows the number of individual messages, regardless of their size, produced per second. This is useful as a growth metric as a different meas‐ ure of producer traffic.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum by(instance) (kafka_server_BrokerTopicMetrics_MeanRate{job=\"$Job\", instance=~\"$Instance\", name=\"MessagesInPerSec\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes In",
   "type": "timeseries",
   "description": "Bytes In, expressed in bytes per second, is useful as a measurement of how much message traffic your brokers are receiving from producing clients. This is a good metric to trend over time to help you determine when you need to expand the cluster or do other growth-related work. It is also useful for evaluating if one broker in a cluster is receiving more traffic than the others, which would indicate that it is necessary to rebalance the partitions in the cluster.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(instance) (kafka_server_BrokerTopicMetrics_MeanRate{job=\"$Job\", instance=~\"$Instance\", name=\"BytesInPerSec\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(kafka_network_RequestMetrics_Count{job=\"$Job\", instance=~\"$Instance\", name=\"RequestBytes\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes Out",
   "type": "timeseries",
   "description": "The Bytes Out Rate shows the rate at which consumers are reading messages out. The outbound bytes rate may scale differently than the inbound bytes rate, thanks to Kafka’s capacity to handle multiple consumers with ease. There are many deployments of Kafka where the outbound rate can easily be six times the inbound rate!",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(kafka_server_BrokerTopicMetrics_Count{job=\"$Job\", instance=~\"$Instance\", name=\"BytesOutPerSec\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$Instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "repeat": "Instance",
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "description": "Percentage of CPU utilization by the selected process, and by the system as a whole.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_ProcessCpuLoad{job=\"$Job\", instance=\"$Instance\"}",
     "legendFormat": "Process"
    },
    {
     "expr": "java_lang_OperatingSystem_CpuLoad{job=\"$Job\", instance=\"$Instance\"}",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "CPU Time Rate of Change",
   "type": "timeseries",
   "description": "The rate of change (increase) in the CPU time used per second by this process. A fairly constant value generally indicates the process is doing its normal work. Some peaks and valleys are expected as the process workload changes.\n\nA constantly or sharply increasing rate of change may be indicative of a problem.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(java_lang_OperatingSystem_ProcessCpuTime{job=\"$Job\", instance=\"$Instance\"}[$__rate_interval])",
     "legendFormat": "Change"
    }
   ]
  },
  {
   "title": "System Load Average",
   "type": "timeseries",
   "description": "The average load in the host system.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_SystemLoadAverage{job=\"$Job\", instance=\"$Instance\"}",
     "legendFormat": "Load"
    }
   ]
  }
 ]
}