{
 "title": "Connectors",
 "tags": [
  "Kafka",
  "AKD",
  "Connector",
  "Prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Job",
    "query": {
     "query": "label_values(kafka_server_ControllerMutation_queue_size,job)"
    }
   },
   {
    "name": "Instance",
    "label": "Connector",
    "query": {
     "query": "label_values(kafka_connect_connect_worker_metrics_connector_count{job=\"$Job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Key Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Kafka Brokers", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 } },
  { "title": "Active Controllers", "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 } },
  { "title": "Partitions", "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 } },
  { "title": "Under-Replicated Partitions", "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 } },
  { "title": "Offline Partitions", "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 } },
  { "title": "ZooKeeper Nodes", "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 } },
  { "title": "$Instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "Instance" },
  {
   "title": "Sink Records Read",
   "type": "timeseries",
   "description": "Before transformations are applied, this is the average per-second number of records read from Kafka for the task belonging to the named sink connector in the worker.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "sum by(connector) (kafka_connect_sink_task_metrics_sink_record_read_rate{job=\"$Job\", instance=\"$Instance\"})",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "Sink Records Sent",
   "type": "timeseries",
   "description": "After transformations are applied, this is the average per-second number of records output from the transformations and sent to the task belonging to the named sink connector in the worker (excludes any records filtered out by the transformations).",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "sum by(connector) (kafka_connect_sink_task_metrics_sink_record_send_rate{job=\"$Job\", instance=\"$Instance\"})",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "Source Records Polled",
   "type": "timeseries",
   "description": "Before transformations are applied, this is the average per-second number of records produced or polled by the task belonging to the named source connector in the worker.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "sum by(connector) (kafka_connect_source_task_metrics_source_record_poll_rate{job=\"$Job\", instance=\"$Instance\"})",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "Source Records Written",
   "type": "timeseries",
   "description": "After transformations are applied, this is the average per-second number of records output from the transformations and written to Kafka for the task belonging to the named source connector in the worker (excludes any records filtered out by the transformations).",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "sum by(connector) (kafka_connect_source_task_metrics_source_record_write_rate{job=\"$Job\", instance=\"$Instance\"})",
     "legendFormat": "{{connector}}"
    }
   ]
  }
 ]
}