{
 "title": "Consumers",
 "tags": [
  "Kafka",
  "AKD",
  "Consumer",
  "Prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Job",
    "query": {
     "query": "label_values(kafka_server_ControllerMutation_queue_size,job)"
    }
   },
   {
    "name": "Instance",
    "label": "Consumer",
    "query": {
     "query": "label_values(kafka_consumer_kafka_metrics_count_count{job=\"$Job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Key Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  { "title": "Kafka Brokers", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 } },
  { "title": "Active Controllers", "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 } },
  { "title": "Partitions", "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 } },
  { "title": "Under-Replicated Partitions", "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 } },
  { "title": "Offline Partitions", "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 } },
  { "title": "ZooKeeper Nodes", "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 } },
  {
   "title": "$Instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "repeat": "Instance",
   "targets": [
    {}
   ]
  },
  {
   "title": "Records Lag",
   "type": "timeseries",
   "description": "The latest lag in terms of records for this topic and partition.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_records_lag{job=\"$Job\", instance=\"$Instance\"}",
     "legendFormat": "{{topic}} partition {{partition}}"
    }
   ]
  },
  {
   "title": "Records Lag Max",
   "type": "timeseries",
   "description": "The maximum lag in terms of records for this topic and partition.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_records_lag_max{job=\"$Job\", instance=\"$Instance\", topic=\"\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_records_lag_max{job=\"$Job\", instance=\"$Instance\", topic!=\"\"}",
     "legendFormat": "Topic {{topic}} partition {{partition}}"
    }
   ]
  },
  {
   "title": "Bytes Consumed Rate",
   "type": "timeseries",
   "description": "The average number of bytes consumed per second.",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_bytes_consumed_rate{job=\"$Job\", instance=\"$Instance\",topic=\"\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_bytes_consumed_rate{job=\"$Job\", instance=\"$Instance\", topic!=\"\"}",
     "legendFormat": "Topic {{topic}}"
    }
   ]
  },
  {
   "title": "Records Consumed Rate",
   "type": "timeseries",
   "description": "The average number of records consumed per second.",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_records_consumed_rate{job=\"$Job\", instance=\"$Instance\", topic=\"\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_records_consumed_rate{job=\"$Job\", instance=\"$Instance\", topic!=\"\"}",
     "legendFormat": "Topic {{topic}}"
    }
   ]
  },
  {
   "title": "Fetch Rate",
   "type": "timeseries",
   "description": "The number of fetch requests per second.",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_rate{job=\"$Job\", instance=\"$Instance\"}",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}