{
 "title": "Logs by Topic",
 "tags": [
  "AKD",
  "Kafka",
  "Broker",
  "Logs",
  "Topics",
  "Prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Job",
    "query": {
     "query": "label_values(kafka_server_ControllerMutation_queue_size,job)"
    }
   },
   {
    "name": "Topic",
    "query": {
     "query": "label_values(kafka_server_BrokerTopicMetrics_Count{job=\"$Job\", name=\"MessagesInPerSec\"},topic)"
    }
   },
   {
    "name": "Instance",
    "label": "Broker",
    "query": {
     "query": "label_values(kafka_server_BrokerTopicMetrics_Count{job=\"$Job\", topic=~\"$Topic\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Key Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Kafka Brokers", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 } },
  { "title": "Active Controllers", "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 } },
  { "title": "Partitions", "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 } },
  { "title": "Under-Replicated Partitions", "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 } },
  { "title": "Offline Partitions", "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 } },
  { "title": "ZooKeeper Nodes", "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 } },
  { "title": "$Topic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "Topic" },
  {
   "title": "Partitions",
   "type": "timeseries",
   "description": "Total number of partitions for the topic for a given broker.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by(instance, topic) (kafka_log_Log_Value{job=\"$Job\", topic=\"$Topic\", instance=~\"$Instance\", name=\"Size\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Segments",
   "type": "timeseries",
   "description": "Total number of log file segments for the topic on a given broker.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(instance, topic) (kafka_log_Log_Value{job=\"$Job\", topic=\"$Topic\", instance=~\"$Instance\", name=\"NumLogSegments\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "timeseries",
   "description": "Total number of messages in the topic for all partitions on a given broker.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance, topic) (kafka_log_Log_Value{job=\"$Job\", instance=~\"$Instance\", topic=\"$Topic\", name=\"LogEndOffset\"} - ignoring(name) kafka_log_Log_Value{job=\"$Job\", instance=~\"$Instance\", topic=\"$Topic\", name=\"LogStartOffset\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Message Bytes (1K=1000)",
   "type": "timeseries",
   "description": "Total message bytes in the topic for all partitions on a given broker.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(instance, topic) (kafka_log_Log_Value{job=\"$Job\", instance=~\"$Instance\", topic=\"$Topic\", name=\"Size\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Approximate Total Bytes (1K=1000)",
   "type": "timeseries",
   "description": "Approximate disk space used by the topic across all partitions on a given broker. This includes message bytes and overhead used by index files.\n\nThis number is an approximation, and is computed based on the number of messages in the topic and the expected index overhead for each message.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (instance, topic) (((kafka_log_Log_Value{job=\"$Job\", instance=~\"$Instance\", topic=\"$Topic\", name=\"LogEndOffset\"} - ignoring(name) kafka_log_Log_Value{job=\"$Job\", instance=~\"$Instance\", topic=\"$Topic\", name=\"LogStartOffset\"}) * 20) + ignoring(name) kafka_log_Log_Value{job=\"$Job\", instance=~\"$Instance\", topic=\"$Topic\", name=\"Size\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}