{
 "title": "Broker Request / Response",
 "tags": [
  "AKD",
  "Broker",
  "Kafka",
  "Prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Job",
    "query": {
     "query": "label_values(kafka_server_ControllerMutation_queue_size,job)"
    }
   },
   {
    "name": "Instance",
    "label": "Broker",
    "query": {
     "query": "label_values(kafka_server_ControllerMutation_queue_size{job=\"$Job\"},instance)"
    }
   },
   {
    "name": "fields",
    "label": "Percentile",
    "query": "95thPercentile, 98thPercentile, 99thPercentile, 999thPercentile"
   }
  ]
 },
 "panels": [
  { "title": "Key Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Kafka Brokers", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 } },
  { "title": "Active Controllers", "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 } },
  { "title": "Partitions", "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 } },
  { "title": "Under-Replicated Partitions", "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 } },
  { "title": "Offline Partitions", "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 } },
  { "title": "ZooKeeper Nodes", "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 } },
  { "title": "$Instance Latency - $fields", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "Instance" },
  {
   "title": "Produce",
   "type": "timeseries",
   "description": "Request queue time: \nThe amount of time the request spends in queue after it has been received but before processing starts.\n\nLocal time: \nThe amount of time the partition leader spends processing a request, including sending it to disk (but not necessarily flushing it).\n\nRemote time: \nThe amount of time spent waiting for the followers before request processing can complete.\n\nResponse queue time:\nThe amount of time the response to the request spends in the queue before it can be sent to the requestor.\n\nResponse send time:\nThe amount of time spent actually sending the response.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "repeat": "brokername",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "{__name__=~\"kafka_network_RequestMetrics_$fields\", job=\"$Job\",instance=~\"$Instance\",request=\"Produce\",name=~\".*TimeMs\"}",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Fetch Follower ",
   "type": "timeseries",
   "description": "Request queue time: \nThe amount of time the request spends in queue after it has been received but before processing starts.\n\nLocal time: \nThe amount of time the partition leader spends processing a request, including sending it to disk (but not necessarily flushing it).\n\nRemote time: \nThe amount of time spent waiting for the followers before request processing can complete.\n\nResponse queue time:\nThe amount of time the response to the request spends in the queue before it can be sent to the requestor.\n\nResponse send time:\nThe amount of time spent actually sending the response.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "repeat": "brokername",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "{__name__=~\"kafka_network_RequestMetrics_$fields\", job=\"$Job\",instance=~\"$Instance\",request=\"FetchFollower\",name=~\".*TimeMs\"}",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Fetch Consumer",
   "type": "timeseries",
   "description": "Request queue time: \nThe amount of time the request spends in queue after it has been received but before processing starts.\n\nLocal time: \nThe amount of time the partition leader spends processing a request, including sending it to disk (but not necessarily flushing it).\n\nRemote time: \nThe amount of time spent waiting for the followers before request processing can complete.\n\nResponse queue time:\nThe amount of time the response to the request spends in the queue before it can be sent to the requestor.\n\nResponse send time:\nThe amount of time spent actually sending the response.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "repeat": "brokername",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "{__name__=~\"kafka_network_RequestMetrics_$fields\", job=\"$Job\",instance=~\"$Instance\",request=\"FetchConsumer\",name=~\".*TimeMs\"}",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  }
 ]
}