{
 "title": "Broker Health",
 "tags": [
  "Kafka",
  "AKD",
  "Broker",
  "Prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Job",
    "query": {
     "query": "label_values(kafka_server_ControllerMutation_queue_size,job)"
    }
   },
   {
    "name": "Instance",
    "label": "Broker",
    "query": {
     "query": "label_values(kafka_server_ControllerMutation_queue_size{job=\"$Job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Key Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Kafka Brokers", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 } },
  { "title": "Active Controllers", "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 } },
  { "title": "Partitions", "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 } },
  { "title": "Under-Replicated Partitions", "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 } },
  { "title": "Offline Partitions", "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 } },
  { "title": "ZooKeeper Nodes", "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 } },
  {
   "title": "Messages In",
   "type": "timeseries",
   "description": "The Messages In Rate shows the number of individual messages, regardless of their size, produced per second. This is useful as a growth metric as a different measure of producer traffic.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum by(instance) (kafka_server_BrokerTopicMetrics_MeanRate{job=\"$Job\", instance=~\"$Instance\", name=\"MessagesInPerSec\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes In",
   "type": "timeseries",
   "description": "Bytes In, expressed in bytes per second, is useful as a measurement of how much message traffic your brokers are receiving from producing clients. This is a good metric to trend over time to help you determine when you need to expand the cluster or do other growth-related work. It is also useful for evaluating if one broker in a cluster is receiving more traffic than the others, which would indicate that it is necessary to rebalance the partitions in the cluster.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(instance) (kafka_server_BrokerTopicMetrics_MeanRate{job=\"$Job\", instance=~\"$Instance\", name=\"BytesInPerSec\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Bytes",
   "type": "timeseries",
   "description": "Request bytes received per second.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(kafka_network_RequestMetrics_Count{job=\"$Job\", instance=~\"$Instance\", name=\"RequestBytes\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes Out",
   "type": "timeseries",
   "description": "The Bytes Out Rate shows the rate at which consumers are reading messages out. The outbound bytes rate may scale differently than the inbound bytes rate, thanks to Kafka’s capacity to handle multiple consumers with ease. There are many deployments of Kafka where the outbound rate can easily be six times the inbound rate!",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(kafka_server_BrokerTopicMetrics_Count{job=\"$Job\", instance=~\"$Instance\", name=\"BytesOutPerSec\", topic=\"\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "timeseries",
   "description": "The total number of partitions for which a broker is the leader replica, where the follower replicas are not caught up. This single measurement provides insight into a number of problems with the Kafka cluster, from a broker being down to resource exhaustion.\n\nValue greater than 0 should be looked into.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_server_ReplicaManager_Value{job=\"$Job\", instance=~\"$Instance\", name=\"UnderReplicatedPartitions\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Request Time - Fetch",
   "type": "timeseries",
   "description": "Total time to service the Fetch request.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_network_RequestMetrics_99thPercentile{job=\"$Job\", instance=~\"$Instance\", name=\"TotalTimeMs\", request=\"Fetch\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Request Time - Produce",
   "type": "timeseries",
   "description": "Total time to service the Produce request.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_network_RequestMetrics_99thPercentile{job=\"$Job\", instance=~\"$Instance\", request=\"Produce\", name=\"TotalTimeMs\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Request Time - Fetch Consumer",
   "type": "timeseries",
   "description": "Total time to service the Fetch Consumer request.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_network_RequestMetrics_99thPercentile{job=\"$Job\", instance=~\"$Instance\", request=\"FetchConsumer\", name=\"TotalTimeMs\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Leader Election",
   "type": "timeseries",
   "description": "Non-zero when there are broker failures.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(kafka_controller_ControllerStats_Count{job=\"$Job\", instance=~\"$Instance\", name=\"LeaderElectionRateAndTimeMs\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Unclean Leader Election",
   "type": "timeseries",
   "description": "Unclear Leader Election is when we allow out-of-sync replicas to become leaders, we risk data loss and data inconsistencies. If we don’t allow them to become leaders, we face lower availa‐ bility as we must wait for the original leader to become available before the partition is back online.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(kafka_controller_ControllerStats_Count{job=\"$Job\", instance=~\"$Instance\", name=\"UncleanLeaderElectionEnableRateAndTimeMs\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ISR Expand",
   "type": "timeseries",
   "description": "If a broker goes down, ISR for some of the partitions will shrink. When that broker is up again, ISR will be expanded once the replicas are fully caught up. Other than that, the expected value for both ISR shrink rate and expansion rate is 0.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kafka_server_ReplicaManager_Count{job=\"$Job\", instance=~\"$Instance\", name=\"IsrExpandsPerSec\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ISR Shrink",
   "type": "timeseries",
   "description": "If a broker goes down, ISR for some of the partitions will shrink. When that broker is up again, ISR will be expanded once the replicas are fully caught up. Other than that, the expected value for both ISR shrink rate and expansion rate is 0.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kafka_server_ReplicaManager_Count{job=\"$Job\", instance=~\"$Instance\", name=\"IsrShrinksPerSec\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Delayed Operation Fetch Purgatory Size",
   "type": "timeseries",
   "description": "Number of requests waiting in the fetch purgatory. This is high if consumers use a large value for fetch.wait.max.ms.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_server_DelayedOperationPurgatory_Value{job=\"$Job\", instance=~\"$Instance\", name=\"PurgatorySize\", delayedOperation=\"Fetch\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Delayed Operation Produce Purgatory Size",
   "type": "timeseries",
   "description": "Number of requests waiting in the producer purgatory. This should be non-zero when acks=all is used on the producer.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_server_DelayedOperationPurgatory_Value{job=\"$Job\", instance=~\"$Instance\", delayedOperation=\"Produce\", name=\"PurgatorySize\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Handler Pool Idle",
   "type": "timeseries",
   "description": "Average percent of time the request handler threads are idle.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kafka_server_KafkaRequestHandlerPool_FifteenMinuteRate{job=\"$Job\", instance=~\"$Instance\", name=\"RequestHandlerAvgIdlePercent\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Temporary Memory Bytes",
   "type": "timeseries",
   "description": "The number of bytes of temporary memory used for message format conversions and decompression.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kafka_network_RequestMetrics_Count{job=\"$Job\", instance=~\"$Instance\", name=\"TemporaryMemoryBytes\", request=~\"Fetch|Produce\"}",
     "legendFormat": "{{instance}} {{request}}"
    }
   ]
  },
  {
   "title": "Broker Start Time",
   "type": "table",
   "description": "The date and time each broker was last started.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "kafka_server_app_info_start_time_ms{job=~\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Reporting Clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count by(instance, id) (kafka_consumer_app_info_StartTimeMs{job=\"$Job\"}))",
     "legendFormat": "Consumers"
    },
    {
     "expr": "sum(count by(instance, id) (kafka_producer_app_info_StartTimeMs{job=\"$Job\"}))",
     "legendFormat": "Producers"
    },
    {
     "expr": "sum(count by(instance, id) (kafka_connector_app_info_StartTimeMs{job=\"$Job\"}))",
     "legendFormat": "Connectors"
    }
   ]
  }
 ]
}