/*
 * Copyright (c) 2018: 2016-12-13 11:04:42 -0800 (Tue, 13 Dec 2016) $ TIBCO Software Inc.
 * Licensed under a BSD-style license. Refer to [LICENSE]
 * For more information, please contact:
 * TIBCO Software Inc., Palo Alto, California, USA
 *
 * $Id: version.h.config 90137 2016-12-13 19:04:42Z rselph $
 *
 */

#ifndef INCLUDED_TIBEFTL_VERSION_H
#define INCLUDED_TIBEFTL_VERSION_H

#define EFTL_VERSION_MAJOR_NUM   @EFTL_VERSION_MAJOR@
#define EFTL_VERSION_MINOR_NUM   @EFTL_VERSION_MINOR@
#define EFTL_VERSION_UPDATE_NUM  @EFTL_VERSION_UPDATE@
#define EFTL_VERSION_BUILD_NUM   @EFTL_VERSION_BUILD@

#define EFTL_VERSION_MAJOR_STRING    "@EFTL_VERSION_MAJOR@"
#define EFTL_VERSION_MINOR_STRING    "@EFTL_VERSION_MINOR@"
#define EFTL_VERSION_UPDATE_STRING   "@EFTL_VERSION_UPDATE@"
#define EFTL_VERSION_BUILD_STRING    "@EFTL_VERSION_BUILD@"

#define EFTL_VERSION_STRING_COMPARE  "@EFTL_VERSION_MAJOR@.@EFTL_VERSION_MINOR@.@EFTL_VERSION_UPDATE@ @EFTL_VERSION_RELEASE_TYPE@"

#define EFTL_VERSION_STRING_SHORT    "@EFTL_VERSION_MAJOR@.@EFTL_VERSION_MINOR@.@EFTL_VERSION_UPDATE@ @EFTL_VERSION_RELEASE_TYPE@ V@EFTL_VERSION_BUILD@"

#define EFTL_VERSION_STRING_LONG     "TIBCO eFTL Version " EFTL_VERSION_STRING_SHORT "@TIB_SVN_VERSION_LONG@"

#define EFTL_VERSION_BANNER  EFTL_VERSION_STRING_LONG "\nCopyright @TIB_COPYRIGHT_YEARS@ TIBCO Software Inc.\n" \
                      "Licensed under a BSD-style license. Refer to [LICENSE]\n"
                      
#endif /* INCLUDED_TIBEFTL_VERSION_H */
