{
 "title": "Broker",
 "tags": [
  "APD",
  "Pulsar",
  "Prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Job",
    "query": {
     "query": "query_result(count(last_over_time(pulsar_active_connections[${__range}])) by (job))"
    }
   },
   {
    "name": "Instance",
    "label": "Broker",
    "query": {
     "query": "query_result(count(last_over_time(pulsar_active_connections{job =~ \"${Job}\"}[${__range}])) by (instance))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Managed Ledger Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Evictions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pulsar_ml_cache_evictions{job=~\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Insertion rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "rate(pulsar_ml_cache_inserted_entries_total{job=~\"$Job\", instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Eviction rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "rate(pulsar_ml_cache_evicted_entries_total{job=~\"$Job\", instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Entries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pulsar_ml_cache_entries{job=~\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Hits rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "pulsar_ml_cache_hits_rate{job=~\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}} Succeeded"
    }
   ]
  },
  {
   "title": "Hits throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "pulsar_ml_cache_hits_throughput{job=~\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Misses rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "pulsar_ml_cache_misses_rate{job=~\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Misses throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "pulsar_ml_cache_misses_throughput{job=~\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pool active allocations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pulsar_ml_cache_pool_active_allocations_huge{job=~\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}} Huge"
    },
    {
     "expr": "pulsar_ml_cache_pool_active_allocations_normal{job=~\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}} Normal"
    },
    {
     "expr": "pulsar_ml_cache_pool_active_allocations_small{job=~\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}} Small"
    }
   ]
  },
  {
   "title": "Pool allocated",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pulsar_ml_cache_pool_allocated{job=~\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pool used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pulsar_ml_cache_pool_used{job=~\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pulsar_ml_cache_used_size{job=~\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Broker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Managed ledgers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pulsar_ml_count{job=~\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pulsar_active_connections{job=~\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connections created",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pulsar_connection_create_success_count{job=~\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}} Success"
    },
    {
     "expr": "pulsar_connection_create_fail_count{job=~\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}} Failure"
    }
   ]
  },
  {
   "title": "Connections throttled",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pulsar_broker_throttled_connections{job=~\"$Job\", instance=~\"$Instance\"} + pulsar_broker_throttled_connections_global_limit{job=~\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connections closed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pulsar_connection_closed_total_count{job=~\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Topics",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pulsar_broker_topics_count{job=~\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pulsar_broker_subscriptions_count{job=~\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Producers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pulsar_broker_producers_count{job=~\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pulsar_broker_consumers_count{job=~\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Message rate in",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "pulsar_broker_rate_in{job=~\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Throughput in",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "pulsar_broker_throughput_in{job=~\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Message rate out",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "pulsar_broker_rate_out{job=~\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Throughput out",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "pulsar_broker_throughput_out{job=~\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Storage size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pulsar_broker_storage_size{job=~\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Storage logical size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pulsar_broker_storage_logical_size{job=~\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Storage write rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "pulsar_broker_storage_write_rate{job=~\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Storage read rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "pulsar_broker_storage_read_rate{job=~\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Message backlog",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pulsar_broker_msg_backlog{job=~\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}