{
 "title": "Topic",
 "tags": [
  "APD",
  "Topic",
  "Pulsar",
  "Prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Job",
    "query": {
     "query": "query_result(count(last_over_time(pulsar_rate_in[${__range}])) by (job))"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "query_result(count(last_over_time({job =~ \"${Job}\"}[${__range}])) by (cluster))"
    }
   },
   {
    "name": "Topic",
    "query": {
     "query": "query_result(count(last_over_time(pulsar_rate_in{job =~ \"${Job}\", cluster =~ \"${Cluster}\"}[${__range}])) by (topic))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Local publish rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum by(topic) (pulsar_rate_in{cluster=~\"$Cluster\", topic=~\"$Topic\", job=~\"$Job\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Local publish throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(topic) (pulsar_throughput_in{cluster=~\"$Cluster\", topic=~\"$Topic\", job=~\"$Job\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Local delivery rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum by(topic) (pulsar_subscription_msg_rate_out{cluster=~\"$Cluster\", topic=~\"$Topic\", job=~\"$Job\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Local delivery throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(topic) (pulsar_subscription_msg_throughput_out{cluster=~\"$Cluster\", topic=~\"$Topic\", job=~\"$Job\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Producers - Subscriptions - Consumers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(topic) (pulsar_producers_count{cluster=~\"$Cluster\", topic=~\"$Topic\", job=~\"$Job\"})",
     "legendFormat": "{{topic}} producers"
    },
    {
     "expr": "sum by(topic) (pulsar_subscriptions_count{cluster=~\"$Cluster\", topic=~\"$Topic\", job=~\"$Job\"})",
     "legendFormat": "{{topic}} subscriptions"
    },
    {
     "expr": "sum by(topic) (pulsar_consumers_count{cluster=~\"$Cluster\", topic=~\"$Topic\", job=~\"$Job\"})",
     "legendFormat": "{{topic}} consumers"
    }
   ]
  },
  {
   "title": "Local backlog by Subscription",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(topic, subscription) (pulsar_subscription_back_log{cluster=~\"$Cluster\", topic=~\"$Topic\", job=~\"$Job\"})",
     "legendFormat": "{{topic}} ({{subscription}})"
    }
   ]
  },
  {
   "title": "Storage Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(topic) (pulsar_storage_size{cluster=~\"$Cluster\", topic=~\"$Topic\", job=~\"$Job\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "$Topic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }, "repeat": "Topic" },
  {
   "title": "Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pulsar_storage_write_latency_le_0_5{cluster=~\"$Cluster\", topic=\"$Topic\", job=~\"$Job\"}",
     "legendFormat": "<= 0.5ms"
    },
    {
     "expr": "sum by(topic) (pulsar_storage_write_latency_le_1{cluster=~\"$Cluster\", topic=\"$Topic\", job=~\"$Job\"})",
     "legendFormat": "<= 1ms"
    },
    {
     "expr": "pulsar_storage_write_latency_le_5{cluster=~\"$Cluster\", topic=\"$Topic\", job=~\"$Job\"}",
     "legendFormat": "<= 5ms"
    },
    {
     "expr": "pulsar_storage_write_latency_le_10{cluster=~\"$Cluster\", job=~\"$Job\", topic=\"$Topic\"}",
     "legendFormat": "<= 10ms"
    },
    {
     "expr": "pulsar_storage_write_latency_le_20{cluster=~\"$Cluster\", job=~\"$Job\", topic=\"$Topic\"}",
     "legendFormat": "<= 20ms"
    },
    {
     "expr": "pulsar_storage_write_latency_le_50{cluster=~\"$Cluster\", job=~\"$Job\", topic=\"$Topic\"}",
     "legendFormat": "<= 50ms"
    },
    {
     "expr": "pulsar_storage_write_latency_le_100{cluster=~\"$Cluster\", job=~\"$Job\", topic=\"$Topic\"}",
     "legendFormat": "<= 100ms"
    },
    {
     "expr": "pulsar_storage_write_latency_le_200{cluster=~\"$Cluster\", job=~\"$Job\", topic=\"$Topic\"}",
     "legendFormat": "<= 200ms"
    },
    {
     "expr": "pulsar_storage_write_latency_le_1000{cluster=~\"$Cluster\", job=~\"$Job\", topic=\"$Topic\"}",
     "legendFormat": "<= 1000ms"
    },
    {
     "expr": "pulsar_storage_write_latency_overflow{cluster=~\"$Cluster\", job=~\"$Job\", topic=\"$Topic\"}",
     "legendFormat": "> 1000ms"
    }
   ]
  },
  {
   "title": "Storage Entry Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pulsar_entry_size_le_128{cluster=~\"$Cluster\", job=~\"$Job\", topic=\"$Topic\"}",
     "legendFormat": "<= 128b"
    },
    {
     "expr": "pulsar_entry_size_le_512{cluster=~\"$Cluster\", job=~\"$Job\", topic=\"$Topic\"}",
     "legendFormat": "<= 512b"
    },
    {
     "expr": "pulsar_entry_size_le_1_kb{cluster=~\"$Cluster\", job=~\"$Job\", topic=\"$Topic\"}",
     "legendFormat": "<= 1kb"
    },
    {
     "expr": "pulsar_entry_size_le_2_kb{cluster=~\"$Cluster\", job=~\"$Job\", topic=\"$Topic\"}",
     "legendFormat": "<= 2kb"
    },
    {
     "expr": "pulsar_entry_size_le_4_kb{cluster=~\"$Cluster\", job=~\"$Job\", topic=\"$Topic\"}",
     "legendFormat": "<= 4kb"
    },
    {
     "expr": "pulsar_entry_size_le_16_kb{cluster=~\"$Cluster\", job=~\"$Job\", topic=\"$Topic\"}",
     "legendFormat": "<= 16kb"
    },
    {
     "expr": "pulsar_entry_size_le_100_kb{cluster=~\"$Cluster\", job=~\"$Job\", topic=\"$Topic\"}",
     "legendFormat": "<= 100kb"
    },
    {
     "expr": "pulsar_entry_size_le_1_mb{cluster=~\"$Cluster\", job=~\"$Job\", topic=\"$Topic\"}",
     "legendFormat": "<= 1mb"
    },
    {
     "expr": "pulsar_entry_size_le_overflow{cluster=~\"$Cluster\", job=~\"$Job\", topic=\"$Topic\"}",
     "legendFormat": "> 1mb"
    }
   ]
  }
 ]
}