{
 "title": "JVM",
 "tags": [
  "Pulsar",
  "APD",
  "JVM",
  "Prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Job",
    "query": {
     "query": "query_result(count(last_over_time(process_cpu_seconds_total[${__range}])) by (job))"
    }
   },
   {
    "name": "Instance",
    "query": {
     "query": "query_result(count(last_over_time({job =~ \"${Job}\"}[${__range}])) by (instance))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$Instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "Instance",
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$Job\", instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "CPU time"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_committed{job=~\"$Job\", instance=~\"$Instance\", area=\"heap\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "jvm_memory_bytes_used{job=~\"$Job\", instance=~\"$Instance\", area=\"heap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_bytes_max{job=~\"$Job\", instance=~\"$Instance\", area=\"heap\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Non-Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_committed{job=~\"$Job\", instance=~\"$Instance\", area=\"nonheap\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "jvm_memory_bytes_used{job=~\"$Job\", instance=~\"$Instance\", area=\"nonheap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_bytes_max{job=~\"$Job\", instance=~\"$Instance\", area=\"nonheap\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "GC Pauses",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{job=~\"$Job\", instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  }
 ]
}