{
 "title": "BookKeeper",
 "tags": [
  "APD",
  "Pulsar",
  "BookKeeper",
  "Prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Job",
    "query": {
     "query": "query_result(count(last_over_time(bookie_SERVER_STATUS[${__range}])) by (job))"
    }
   },
   {
    "name": "Instance",
    "label": "Bookkeeper",
    "query": {
     "query": "query_result(count(last_over_time(bookie_SERVER_STATUS{job =~ \"${Job}\"}[${__range}])) by (instance))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Add entry rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(bookkeeper_server_ADD_ENTRY_count{job=~\"$Job\", instance=~\"$Instance\", success=\"true\"}[$__rate_interval])",
     "legendFormat": "{{instance}} Succeeded"
    },
    {
     "expr": "rate(bookkeeper_server_ADD_ENTRY_count{job=~\"$Job\", instance=~\"$Instance\", success=\"false\"}[$__rate_interval])",
     "legendFormat": "{{instance}} Failed"
    }
   ]
  },
  {
   "title": "Add entry latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "bookkeeper_server_ADD_ENTRY_REQUEST{job=~\"$Job\", instance=~\"$Instance\", success=\"true\", quantile=\"0.5\"}",
     "legendFormat": "{{instance}} 50%"
    },
    {
     "expr": "bookkeeper_server_ADD_ENTRY_REQUEST{job=~\"$Job\", instance=~\"$Instance\", success=\"true\", quantile=\"0.99\"}",
     "legendFormat": "{{instance}} 99%"
    }
   ]
  },
  {
   "title": "Write throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(bookie_WRITE_BYTES{job=~\"$Job\", instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Read entry rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(bookkeeper_server_READ_ENTRY_count{job=~\"$Job\", instance=~\"$Instance\", success=\"true\"}[$__rate_interval])",
     "legendFormat": "{{instance}} Succeeded"
    },
    {
     "expr": "rate(bookkeeper_server_READ_ENTRY_count{job=~\"$Job\", instance=~\"$Instance\", success=\"false\"}[$__rate_interval])",
     "legendFormat": "{{instance}} Failed"
    }
   ]
  },
  {
   "title": "Read entry latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "bookkeeper_server_READ_ENTRY_REQUEST{job=~\"$Job\", instance=~\"$Instance\", success=\"true\", quantile=\"0.5\"}",
     "legendFormat": "{{instance}} 50%"
    },
    {
     "expr": "bookkeeper_server_READ_ENTRY_REQUEST{job=~\"$Job\", instance=~\"$Instance\", success=\"true\", quantile=\"0.99\"}",
     "legendFormat": "{{instance}} 99%"
    }
   ]
  },
  {
   "title": "Read throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(bookie_READ_BYTES{job=~\"$Job\", instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Journal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Journal Queue latency (Max)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "bookie_journal_JOURNAL_QUEUE_LATENCY{job=~\"$Job\", instance=~\"$Instance\", quantile=\"1.0\", success=\"true\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Journal Queue length",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(instance) (bookie_journal_JOURNAL_QUEUE_SIZE{job=~\"$Job\", instance=~\"$Instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Journal Sync Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(bookie_journal_JOURNAL_SYNC_count{job=~\"$Job\", instance=~\"$Instance\", success=\"true\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Journal Sync Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "bookie_journal_JOURNAL_SYNC{job=~\"$Job\", instance=~\"$Instance\", quantile=\"1.0\", success=\"true\"}",
     "legendFormat": "{{instance}} Success"
    },
    {
     "expr": "bookie_journal_JOURNAL_SYNC{job=~\"$Job\", instance=~\"$Instance\", quantile=\"1.0\", success=\"false\"}",
     "legendFormat": "{{instance}} Failurel"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Ledgers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bookie_ledgers_count{job=~\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Entries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bookie_entries_count{job=~\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Deleted Ledgers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
   "targets": [
    {
     "expr": "bookie_DELETED_LEDGER_TOTAL{job=~\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Read Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "bookie_read_cache_size{job=~\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Write Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "bookie_write_cache_size{job=~\"$Job\", instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}