{
 "title": "Connections",
 "tags": [
  "APD",
  "Prometheus",
  "Pulsar"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Job",
    "query": {
     "query": "query_result(count(last_over_time(pulsar_active_connections[${__range}])) by (job))"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "query_result(count(last_over_time({job =~ \"${Job}\"}[${__range}])) by (cluster))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Active",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum by(job) (sum by(instance) (pulsar_active_connections{job=~\"$Job\"})))",
     "legendFormat": "Active connections"
    }
   ]
  },
  {
   "title": "Producers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum by(job) (sum by(instance) (pulsar_producers_count{job=~\"$Job\"})))",
     "legendFormat": "Producers"
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum by(job) (sum by(instance) (pulsar_consumers_count{job=~\"$Job\"})))",
     "legendFormat": "Consumers"
    }
   ]
  },
  {
   "title": "Proxy",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum by(job) (sum by(instance) (pulsar_proxy_active_connections{job=~\"$Job\"})))",
     "legendFormat": "Consumers"
    }
   ]
  },
  {
   "title": "Active",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by(job) (sum by(instance) (pulsar_active_connections{job=~\"$Job\"})))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(sum(sum by(job) (sum by(instance) (pulsar_active_connections{job=~\"$Job\"}))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producers",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by(job) (sum by(instance) (pulsar_producers_count{job=~\"$Job\"})))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(sum(sum by(job) (sum by(instance) (pulsar_producers_count{job=~\"$Job\"}))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by(job) (sum by(instance) (pulsar_consumers_count{job=~\"$Job\"})))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(sum(sum by(job) (sum by(instance) (pulsar_consumers_count{cluster=~\"$Cluster\", job=~\"$Job\"}))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxy",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by(job) (sum by(instance) (pulsar_proxy_active_connections{job=~\"$Job\"})))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(sum(sum by(job) (sum by(instance) (pulsar_proxy_active_connections{job=~\"$Job\"}))))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}