{
 "title": "Namespace",
 "tags": [
  "APD",
  "Namespace",
  "Pulsar",
  "Prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Job",
    "query": {
     "query": "query_result(count(last_over_time(pulsar_topics_count[${__range}])) by (job))"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "query_result(count(last_over_time({job =~ \"${Job}\"}[${__range}])) by (cluster))"
    }
   },
   {
    "name": "Namespace",
    "query": {
     "query": "query_result(count(last_over_time({job =~ \"${Job}\", cluster =~ \"${Cluster}\"}[${__range}])) by (namespace))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Local publish rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum by(namespace) (pulsar_rate_in{job=~\"$Job\", namespace=~\"$Namespace\", cluster=~\"$Cluster\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Local publish throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(namespace) (pulsar_throughput_in{job=~\"$Job\", namespace=~\"$Namespace\", cluster=~\"$Cluster\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Local delivery rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum by(namespace) (pulsar_rate_out{job=~\"$Job\", namespace=~\"$Namespace\", cluster=~\"$Cluster\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Local delivery throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(namespace) (pulsar_throughput_out{job=~\"$Job\", namespace=~\"$Namespace\", cluster=~\"$Cluster\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Topics - Producers - Subscriptions - Consumers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(namespace) (pulsar_topics_count{job=~\"$Job\", namespace=~\"$Namespace\", cluster=~\"$Cluster\"})",
     "legendFormat": "{{namespace}} Topics"
    },
    {
     "expr": "sum by(namespace) (pulsar_producers_count{job=~\"$Job\", namespace=~\"$Namespace\", cluster=~\"$Cluster\"})",
     "legendFormat": "{{namespace}} Producers"
    },
    {
     "expr": "sum by(namespace) (pulsar_subscriptions_count{job=~\"$Job\", namespace=~\"$Namespace\", cluster=~\"$Cluster\"})",
     "legendFormat": "{{namespace}} Subscriptions"
    },
    {
     "expr": "sum by(namespace) (pulsar_consumers_count{job=~\"$Job\", namespace=~\"$Namespace\", cluster=~\"$Cluster\"})",
     "legendFormat": "{{namespace}} Consumers"
    }
   ]
  },
  {
   "title": "Local backlog",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(namespace) (pulsar_msg_backlog{job=~\"$Job\", namespace=~\"$Namespace\", cluster=~\"$Cluster\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Storage Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(namespace) (pulsar_storage_size{job=~\"$Job\", namespace=~\"$Namespace\", cluster=~\"$Cluster\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Storage Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(namespace) (pulsar_storage_write_latency_le_0_5{job=~\"$Job\", namespace=~\"$Namespace\", cluster=~\"$Cluster\"})",
     "legendFormat": "{{namespace}} <= 0.5ms"
    },
    {
     "expr": "sum by(namespace) (pulsar_storage_write_latency_le_1{job=~\"$Job\", namespace=~\"$Namespace\", cluster=~\"$Cluster\"})",
     "legendFormat": "{{namespace}} <= 1ms"
    },
    {
     "expr": "sum by(namespace) (pulsar_storage_write_latency_le_5{job=~\"$Job\", namespace=~\"$Namespace\", cluster=~\"$Cluster\"})",
     "legendFormat": "{{namespace}} <= 5ms"
    },
    {
     "expr": "sum by(namespace) (pulsar_storage_write_latency_le_10{job=~\"$Job\", namespace=~\"$Namespace\", cluster=~\"$Cluster\"})",
     "legendFormat": "{{namespace}} <= 10ms"
    },
    {
     "expr": "sum by(namespace) (pulsar_storage_write_latency_le_20{job=~\"$Job\", namespace=~\"$Namespace\", cluster=~\"$Cluster\"})",
     "legendFormat": "{{namespace}} <= 20ms"
    },
    {
     "expr": "sum by(namespace) (pulsar_storage_write_latency_le_50{job=~\"$Job\", namespace=~\"$Namespace\", cluster=~\"$Cluster\"})",
     "legendFormat": "{{namespace}} <= 50ms"
    },
    {
     "expr": "sum by(namespace) (pulsar_storage_write_latency_le_100{job=~\"$Job\", namespace=~\"$Namespace\", cluster=~\"$Cluster\"})",
     "legendFormat": "{{namespace}} <= 100ms"
    },
    {
     "expr": "sum by(namespace) (pulsar_storage_write_latency_le_200{job=~\"$Job\", namespace=~\"$Namespace\", cluster=~\"$Cluster\"})",
     "legendFormat": "{{namespace}} <= 200ms"
    },
    {
     "expr": "sum by(namespace) (pulsar_storage_write_latency_le_1000{job=~\"$Job\", namespace=~\"$Namespace\", cluster=~\"$Cluster\"})",
     "legendFormat": "{{namespace}} <= 1000ms"
    },
    {
     "expr": "sum by(namespace) (pulsar_storage_write_latency_overflow{job=~\"$Job\", namespace=~\"$Namespace\", cluster=~\"$Cluster\"})",
     "legendFormat": "{{namespace}} > 1000ms"
    }
   ]
  },
  {
   "title": "Incoming replication rate | any → $Cluster",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum by(namespace, remote_cluster) (pulsar_replication_rate_in{job=~\"$Job\", namespace=~\"$Namespace\", cluster=~\"$Cluster\"})",
     "legendFormat": "{{namespace}} from {{remote_cluster}}"
    }
   ]
  },
  {
   "title": "Outgoing replication rate | $Cluster → any",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum by(namespace, remote_cluster) (pulsar_replication_rate_out{job=~\"$Job\", namespace=~\"$Namespace\", cluster=~\"$Cluster\"})",
     "legendFormat": "{{namespace}} to {{remote_cluster}}"
    }
   ]
  },
  {
   "title": "Replication backlog | $Cluster → any",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(namespace, remote_cluster) (pulsar_replication_backlog{cluster=~\"$Cluster\", namespace=~\"$Namespace\", job=~\"$Job\"})",
     "legendFormat": "{{namespace}} to {{remote_cluster}}"
    }
   ]
  },
  {
   "title": "Storage Write Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(namespace) (pulsar_storage_write_rate{job=~\"$Job\", namespace=~\"$Namespace\", cluster=~\"$Cluster\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Storage read entry rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pulsar_storage_read_rate{job=~\"$Job\", namespace=~\"$Namespace\", cluster=~\"$Cluster\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Storage entry size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(namespace) (pulsar_entry_size_le_128{job=~\"$Job\", namespace=~\"$Namespace\", cluster=~\"$Cluster\"})",
     "legendFormat": "{{namespace}} <= 128B"
    },
    {
     "expr": "sum by(namespace) (pulsar_entry_size_le_512{job=~\"$Job\", namespace=~\"$Namespace\", cluster=~\"$Cluster\"})",
     "legendFormat": "{{namespace}} <= 512B"
    },
    {
     "expr": "sum by(namespace) (pulsar_entry_size_le_1_kb{job=~\"$Job\", namespace=~\"$Namespace\", cluster=~\"$Cluster\"})",
     "legendFormat": "{{namespace}} <= 1KB"
    },
    {
     "expr": "sum by(namespace) (pulsar_entry_size_le_2_kb{job=~\"$Job\", namespace=~\"$Namespace\", cluster=~\"$Cluster\"})",
     "legendFormat": "{{namespace}} <= 2KB"
    },
    {
     "expr": "sum by(namespace) (pulsar_entry_size_le_4_kb{job=~\"$Job\", namespace=~\"$Namespace\", cluster=~\"$Cluster\"})",
     "legendFormat": "{{namespace}} <= 4KB"
    },
    {
     "expr": "sum by(namespace) (pulsar_entry_size_le_16_kb{job=~\"$Job\", namespace=~\"$Namespace\", cluster=~\"$Cluster\"})",
     "legendFormat": "{{namespace}} <= 16KB"
    },
    {
     "expr": "sum by(namespace) (pulsar_entry_size_le_100_kb{job=~\"$Job\", namespace=~\"$Namespace\", cluster=~\"$Cluster\"})",
     "legendFormat": "{{namespace}} <= 100KB"
    },
    {
     "expr": "sum by(namespace) (pulsar_entry_size_le_1_mb{job=~\"$Job\", namespace=~\"$Namespace\", cluster!=\"$Cluster\"})",
     "legendFormat": "{{namespace}} <= 1MB"
    },
    {
     "expr": "sum by(namespace) (pulsar_entry_size_le_overflow{job=~\"$Job\", namespace=~\"$Namespace\", cluster=~\"$Cluster\"})",
     "legendFormat": "{{namespace}} > 1MB"
    }
   ]
  }
 ]
}