// <autogenerated />
using System;
using System.Reflection;
[assembly: global::System.Runtime.Versioning.TargetFrameworkAttribute("WindowsPhone,Version=v8.0", FrameworkDisplayName = "Windows Phone 8.0")]
